/**
 * Icons of the sketch commands (merged into `chrome/icons.ts` COMMAND_ICON)
 * so the adaptive toolbar and command search never show several sketch
 * commands with the same group glyph.
 */
import {
  ArrowDownToLine,
  Check,
  Circle,
  CornerDownRight,
  DraftingCompass,
  Egg,
  Eraser,
  FlipHorizontal2,
  Grid2x2,
  Hexagon,
  Layers2,
  LayoutGrid,
  Link2,
  Pencil,
  PencilRuler,
  Pill,
  RectangleHorizontal,
  Ruler,
  Scissors,
  Slash,
  Spline,
  SquareDashed,
  TextCursorInput,
  Trash2,
  Type,
  Unlink,
  type LucideIcon,
} from 'lucide-react';

import { CONSTRAINT_INFO } from '../constraintRules.js';

export const SKETCH_COMMAND_ICONS: Record<string, LucideIcon> = {
  'sketch.new': PencilRuler,
  'sketch.newXY': Grid2x2,
  'sketch.newXZ': Grid2x2,
  'sketch.newYZ': Grid2x2,
  'sketch.edit': Pencil,
  'sketch.finish': Check,
  'sketch.line': Slash,
  'sketch.arc': DraftingCompass,
  'sketch.circle': Circle,
  'sketch.rectangle': RectangleHorizontal,
  'sketch.polygon': Hexagon,
  'sketch.trim': Scissors,
  'sketch.offset': Layers2,
  'sketch.dimension': Ruler,
  'sketch.construction': SquareDashed,
  'sketch.deleteSelection': Trash2,
  'sketch.spline': Spline,
  'sketch.slot': Pill,
  'sketch.ellipse': Egg,
  'sketch.text': Type,
  'sketch.fillet': CornerDownRight,
  'sketch.mirror': FlipHorizontal2,
  'sketch.pattern': LayoutGrid,
  'sketch.project': ArrowDownToLine,
  'sketch.toggleReference': Ruler,
  'sketch.editText': TextCursorInput,
  'sketch.deleteCurves': Eraser,
  'sketch.curvesConstruction': SquareDashed,
  'sketch.disconnect': Unlink,
  ...Object.fromEntries(CONSTRAINT_INFO.map((c) => [`sketch.constrain.${c.kind}`, Link2])),
};
