# Generated by scripts/generate-automation-sdk.py; do not edit.
from __future__ import annotations

from enum import Enum
from types import MappingProxyType
from typing import Any, Mapping


class ErrorCode(str, Enum):
    PROTOCOL_MISMATCH = 'protocolMismatch'
    MISSING_CAPABILITY = 'missingCapability'
    INVALID_REQUEST = 'invalidRequest'
    INVALID_CURSOR = 'invalidCursor'
    GENERATION_CHANGED = 'generationChanged'
    PAGE_LIMIT_EXCEEDED = 'pageLimitExceeded'
    BYTE_LIMIT_EXCEEDED = 'byteLimitExceeded'
    CONFLICT = 'conflict'
    LOSS_ACCEPTANCE_REQUIRED = 'lossAcceptanceRequired'
    CONFIRMATION_REQUIRED = 'confirmationRequired'
    OPERATION_NOT_FOUND = 'operationNotFound'
    CANCELLED = 'cancelled'
    LEASE_EXPIRED = 'leaseExpired'
    LEASE_REVOKED = 'leaseRevoked'
    LEASE_RANGE_INVALID = 'leaseRangeInvalid'
    LEASE_BUDGET_EXHAUSTED = 'leaseBudgetExhausted'
    HASH_MISMATCH = 'hashMismatch'
    PERMISSION_DENIED = 'permissionDenied'
    INTERNAL = 'internal'
    UNKNOWN = "unknown"


class HimmelcadError(RuntimeError):
    def __init__(self, *, raw_code: str, message: str, retryable: bool = False, details: Mapping[str, Any] | None = None) -> None:
        try:
            self.code = ErrorCode(raw_code)
        except ValueError:
            self.code = ErrorCode.UNKNOWN
        self.raw_code = raw_code
        self.message = message
        self.retryable = retryable
        self.details = MappingProxyType(dict(details or {}))
        super().__init__(f"{raw_code}: {message}")


class ProtocolError(HimmelcadError):
    pass


class TransportError(HimmelcadError):
    pass


class ValidationError(HimmelcadError):
    pass


class GenerationChangedError(HimmelcadError):
    pass


class LeaseError(HimmelcadError):
    pass


def error_from_payload(payload: Mapping[str, Any]) -> HimmelcadError:
    raw_code = str(payload.get("code", "internal"))
    cls: type[HimmelcadError]
    if raw_code == "generationChanged":
        cls = GenerationChangedError
    elif raw_code.startswith("lease") or raw_code == "hashMismatch":
        cls = LeaseError
    elif raw_code in {"invalidRequest", "invalidCursor", "pageLimitExceeded", "byteLimitExceeded"}:
        cls = ValidationError
    else:
        cls = ProtocolError
    return cls(
        raw_code=raw_code,
        message=str(payload.get("message", "HimmelCAD request failed")),
        retryable=bool(payload.get("retryable", False)),
        details=payload.get("details") if isinstance(payload.get("details"), Mapping) else None,
    )
