# Generated by scripts/generate-automation-sdk.py; do not edit.
from __future__ import annotations

import base64
import hashlib
from typing import TYPE_CHECKING, Any

from .errors import LeaseError
from .models import BulkLeaseDescriptor

if TYPE_CHECKING:
    from .client import AsyncHimmelcadClient, HimmelcadClient

_DTYPES = {
    "uint8": "u1", "int8": "i1", "uint16": "u2", "int16": "i2",
    "uint32": "u4", "int32": "i4", "uint64": "u8", "int64": "i8",
    "float32": "f4", "float64": "f8", "bytes": "u1",
}
_ELEMENT_BYTES = {
    "bytes": 1, "uint8": 1, "int8": 1, "uint16": 2, "int16": 2,
    "uint32": 4, "int32": 4, "uint64": 8, "int64": 8, "float32": 4, "float64": 8,
}
_MAX_SHAPE_ELEMENTS = 2000000000


def _validate_descriptor(descriptor: BulkLeaseDescriptor) -> None:
    elements = 1
    for dimension in descriptor.shape:
        elements *= dimension
        if elements > _MAX_SHAPE_ELEMENTS:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk lease shape exceeds maxShapeElements")
    expected_bytes = elements * _ELEMENT_BYTES[descriptor.element_type]
    if expected_bytes != descriptor.byte_length:
        raise LeaseError(raw_code="leaseRangeInvalid", message="bulk byteLength does not match elementType and shape")
    if descriptor.remaining_read_budget < descriptor.byte_length:
        raise LeaseError(raw_code="leaseBudgetExhausted", message="bulk lease cannot be read completely within its budget")


class BulkLease:
    def __init__(self, client: HimmelcadClient, descriptor: BulkLeaseDescriptor) -> None:
        _validate_descriptor(descriptor)
        self.client = client
        self.descriptor = descriptor
        self.remaining_read_budget = descriptor.remaining_read_budget
        self.released = False

    def __enter__(self) -> BulkLease:
        return self

    def __exit__(self, *_: object) -> None:
        self.release()

    def read(self, offset: int, length: int) -> bytes:
        self._check(offset, length)
        result = self.client._bulk_read(self.descriptor, offset, length)
        data = base64.b64decode(result.data, validate=True)
        if len(data) != result.byte_length or result.offset != offset:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk response range does not match its request")
        self.remaining_read_budget = result.remaining_read_budget
        return data

    def read_all(self) -> bytes:
        chunks = []
        for offset in range(0, self.descriptor.byte_length, self.descriptor.max_readable_range):
            chunks.append(self.read(offset, min(self.descriptor.max_readable_range, self.descriptor.byte_length - offset)))
        data = b"".join(chunks)
        if hashlib.sha256(data).hexdigest() != self.descriptor.content_hash:
            raise LeaseError(raw_code="hashMismatch", message="bulk payload hash does not match its descriptor")
        return data

    def numpy(self) -> Any:
        try:
            import numpy as np
        except ImportError as error:
            raise RuntimeError("install himmelcad[numpy] to use BulkLease.numpy()") from error
        prefix = {"little": "<", "big": ">", "notApplicable": "|"}[self.descriptor.endianness]
        array = np.frombuffer(self.read_all(), dtype=np.dtype(prefix + _DTYPES[self.descriptor.element_type]))
        if self.descriptor.shape:
            expected = 1
            for dimension in self.descriptor.shape:
                expected *= dimension
            if expected != array.size:
                raise LeaseError(raw_code="leaseRangeInvalid", message="lease shape does not match payload size")
            array = array.reshape(self.descriptor.shape)
        array.flags.writeable = False
        return array

    def release(self) -> None:
        if not self.released:
            self.client._bulk_release(self.descriptor)
            self.released = True

    def _check(self, offset: int, length: int) -> None:
        if self.released:
            raise LeaseError(raw_code="leaseRevoked", message="bulk lease was already released")
        if offset < 0 or length <= 0 or offset + length > self.descriptor.byte_length:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk read is outside the described payload")
        if length > self.descriptor.max_readable_range:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk read exceeds maxReadableRange")
        if length > self.remaining_read_budget:
            raise LeaseError(raw_code="leaseBudgetExhausted", message="bulk read exceeds remainingReadBudget")


class AsyncBulkLease:
    def __init__(self, client: AsyncHimmelcadClient, descriptor: BulkLeaseDescriptor) -> None:
        _validate_descriptor(descriptor)
        self.client = client
        self.descriptor = descriptor
        self.remaining_read_budget = descriptor.remaining_read_budget
        self.released = False

    async def __aenter__(self) -> AsyncBulkLease:
        return self

    async def __aexit__(self, *_: object) -> None:
        await self.release()

    async def read(self, offset: int, length: int) -> bytes:
        self._check(offset, length)
        result = await self.client._bulk_read(self.descriptor, offset, length)
        data = base64.b64decode(result.data, validate=True)
        if len(data) != result.byte_length or result.offset != offset:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk response range does not match its request")
        self.remaining_read_budget = result.remaining_read_budget
        return data

    async def read_all(self) -> bytes:
        chunks = []
        for offset in range(0, self.descriptor.byte_length, self.descriptor.max_readable_range):
            chunks.append(await self.read(offset, min(self.descriptor.max_readable_range, self.descriptor.byte_length - offset)))
        data = b"".join(chunks)
        if hashlib.sha256(data).hexdigest() != self.descriptor.content_hash:
            raise LeaseError(raw_code="hashMismatch", message="bulk payload hash does not match its descriptor")
        return data

    async def numpy(self) -> Any:
        try:
            import numpy as np
        except ImportError as error:
            raise RuntimeError("install himmelcad[numpy] to use AsyncBulkLease.numpy()") from error
        prefix = {"little": "<", "big": ">", "notApplicable": "|"}[self.descriptor.endianness]
        array = np.frombuffer(await self.read_all(), dtype=np.dtype(prefix + _DTYPES[self.descriptor.element_type]))
        if self.descriptor.shape:
            expected = 1
            for dimension in self.descriptor.shape:
                expected *= dimension
            if expected != array.size:
                raise LeaseError(raw_code="leaseRangeInvalid", message="lease shape does not match payload size")
            array = array.reshape(self.descriptor.shape)
        array.flags.writeable = False
        return array

    async def release(self) -> None:
        if not self.released:
            await self.client._bulk_release(self.descriptor)
            self.released = True

    def _check(self, offset: int, length: int) -> None:
        if self.released:
            raise LeaseError(raw_code="leaseRevoked", message="bulk lease was already released")
        if offset < 0 or length <= 0 or offset + length > self.descriptor.byte_length:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk read is outside the described payload")
        if length > self.descriptor.max_readable_range:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk read exceeds maxReadableRange")
        if length > self.remaining_read_budget:
            raise LeaseError(raw_code="leaseBudgetExhausted", message="bulk read exceeds remainingReadBudget")
