// Generated by apps/assembler/scripts/generate-skills.mjs from
// assembler/agent-skills/builtin/*/SKILL.md — do not edit; run the script.

/** Built-in assistant skills: id → SKILL.md text (frontmatter + Markdown body). */
export const BUILTIN_SKILL_FILES: Readonly<Record<string, string>> = {
  'api-quickstart': `---
id: api-quickstart
name: Modeling API quick start
description: The hcasm.agent-api@1 calls a part needs, as JSON - sketch profiles, extrude/cut/join, fillet with selectors, shell, holes, references and errors.
version: 1
scope: built-in
tags: [api, modeling]
---

# Modeling API quick start

Units are millimetres, Z is up, the build plate is XY. Every write is one
History step the user can edit and undo. Look up exact parameters with
\`hcasm_methods {method: "…"}\` or a feature kind with
\`hcasm_methods {kind: "extrude"}\`.

## Sketch and extrude

\`\`\`json
{
  "method": "feature.create",
  "params": {
    "kind": "sketch",
    "name": "Base sketch",
    "params": {
      "plane": { "kind": "plane", "plane": "XY", "offset": 0 },
      "profiles": [{ "kind": "rectangle", "x": -40, "y": -25, "width": 80, "height": 50 }]
    }
  }
}
\`\`\`

The result has \`featureId\`, \`regions\` and per shape the dimension names
(\`shapes[0].dimensions.width\`). Circles: \`{"kind": "circle", "cx": 0,
"cy": 0, "radius": 3}\`. More shapes in an existing sketch:
\`sketch.addProfile {featureId, profile}\`; polylines \`sketch.addPolyline\`.

\`\`\`json
{
  "method": "feature.create",
  "params": {
    "kind": "extrude",
    "params": {
      "profile": { "kind": "sketch", "featureId": "sketch-1" },
      "distance": 20,
      "operation": "new",
      "resultBodyName": "Case"
    }
  }
}
\`\`\`

\`operation\`: \`new\`, \`join\`, \`cut\`, \`intersect\` (with \`targetBodyId\`).
Bodies are named \`body:<extrude id>\`. A sketch on a face:
\`"plane": {"kind": "face", "face": {"bodyId": "body:extrude-1", "select": ">Z"}}\`
— its (u, v) are the parallel world axes for axis-aligned faces. An
extrude from a face sketch goes along the face's outward normal: cut into
the material with a **negative** \`distance\` (\`-3\`). A cut that misses the
body removes nothing and is not an error — check \`faceCount\`/\`volume\` in
the result or render it.

## References and selectors

Faces/edges are \`{bodyId, key}\` (from \`faces.list\`/\`edges.list\`) or a
selector \`{bodyId, select}\`: \`>Z\` top-most, \`<Z\` bottom-most, \`+X\` facing
+X, \`|Z\` parallel to Z (edges), \`#Z\` perpendicular, \`%PLANE\`,
\`%CYLINDER\`, \`%CIRCLE\`, combined with \`and\` (\`"|Z and >X"\`).

\`\`\`json
{"method": "feature.create", "params": {"kind": "fillet",
  "params": {"edges": [{"bodyId": "body:extrude-1", "select": "|Z"}], "radius": 4}}}
{"method": "feature.create", "params": {"kind": "shell",
  "params": {"bodyId": "body:extrude-1", "faces": [{"bodyId": "body:extrude-1", "select": ">Z"}],
             "thickness": 2}}}
\`\`\`

## Holes, cut-outs, patterns

- Through holes: circles in a sketch on the face, \`extrude\` with
  \`operation: "cut"\` and \`extent: {"kind": "throughAll"}\` (or a
  distance), or the \`hole\` kind (\`hcasm_methods {kind: "hole"}\`).
- Rows of vents/slots: one slot or rectangle, then \`sketch.pattern\`
  (linear/circular) before the cut — one editable step instead of many.

## Checking

- \`bodies.list\`: \`valid\`, \`bbox.min/max/size\`, \`volume\`.
- \`features.list\`: per step \`error\`/\`warning\`.
- \`print.analyze\`: printability findings (see skill \`fix-printability\`).
- \`view_render\` / \`view_inspect\`: look at it.

## Errors

Errors carry \`code\`, \`message\`, \`hint\` and \`details\`:
\`referenceNotFound\` lists similar keys, \`featureFailed\` names the failing
feature (nothing was committed), \`sketchConflict\` names constraints,
\`busy\` means the user is using a tool — wait and retry, \`conflict\` means
the document changed — re-read it.
`,
  'fix-printability': `---
id: fix-printability
name: Fix printability findings
description: How to read print.analyze findings and fix each kind in the History (overhangs, thin walls, small holes, invalid bodies, build volume) without breaking the part.
version: 1
scope: built-in
tags: [printing, repair]
---

# Fix printability findings

1. \`print.analyze\` (optionally with the user's \`settings\`, e.g.
   \`{material: "PETG", minWallMm: 1.2}\`). Findings have \`kind\`,
   \`severity\`, \`bodyId\`, \`faceKeys\` and a \`message\`.
2. Look at them: \`view_render\` with \`overlay: ["printFindings"]\` colours the
   affected faces (errors red, warnings amber).
3. Fix the most severe first, one change at a time, re-analyse after each.

| Finding                        | Usual fix                                                                                                                                                                                                                                          |
| ------------------------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| \`invalidBrep\`, \`notWatertight\` | Find the step with an error (\`features.list\` → \`error\`), edit or suppress it; avoid zero-thickness joins (overlap joined solids by ≥ 0.01 mm).                                                                                                     |
| \`overhang\`                     | First try orientation: \`print.orientations\` then \`print.orient {bodyId, rank: 1}\`. Else replace the downward face edge with a 45° \`chamfer\`, or add a \`draft\`. Small overhangs below ~5 mm are often fine — say so instead of changing the design. |
| \`thinWall\`                     | Increase the \`shell\`/\`thicken\` thickness or the sketch dimension that makes the wall; the finding's \`value\` is the thinnest sampled thickness.                                                                                                     |
| \`smallHole\`                    | Enlarge the hole to at least \`minHoleMm\` (print clearance +0.2–0.4 mm) or note that it will be drilled.                                                                                                                                            |
| \`smallPin\`                     | Thicken the pin or make it a separate part.                                                                                                                                                                                                        |
| \`buildVolume\`                  | Scale is not a fix; split the part (\`split\`) or ask the user.                                                                                                                                                                                      |
| \`notOnPlate\`                   | \`print.placeOnPlate\` with the face that should touch the plate.                                                                                                                                                                                    |

Rules:

- Edit the feature that causes the problem (\`feature.edit\`,
  \`sketch.setDimension\`, \`parameter.edit\`); do not stack corrective
  features on top when a size can be changed.
- Never delete the user's features to make a finding disappear; deleting
  needs the user's approval anyway.
- Keep the outer dimensions the user asked for unless they agree.
- Finish with a final \`print.analyze\` and list what is left and why.
`,
  'parametric-part': `---
id: parametric-part
name: Parametric part with named parameters
description: Drive a part's key sizes from named document parameters so the user can change them later in the Parameters panel; expression fields, sketch dimensions and rename rules.
version: 1
scope: built-in
tags: [parameters, modeling]
---

# Parametric part with named parameters

Parameters are named document values (\`wall = 2 mm\`) the user edits in the
Parameters panel; every expression field and sketch dimension that names
them follows.

1. Create the parameters first, one call each:
   \`parameter.create {name: "width", value: 80, unit: "mm"}\`,
   \`parameter.create {name: "wall", value: 2, unit: "mm"}\`,
   \`parameter.create {name: "inner_w", expression: "width - 2 * wall"}\`.
   Names: lower case with underscores, short and meaningful.
2. Use them in sketch dimensions: after \`feature.create\` sketch with
   \`profiles\`, the result lists the dimension names of each shape
   (\`{x, y, width, height}\`); bind them with
   \`sketch.setDimension {featureId, dimension: "d3", expression: "width"}\`.
3. Use them in feature sizes: \`extrude\` \`distanceExpression: "height"\`,
   \`fillet\` \`radiusExpression\`, \`chamfer\` \`distanceExpression\`, \`shell\`
   \`thicknessExpression\`, \`hole\` \`diameterExpression\`.
4. Check that the model follows: change a value with
   \`parameter.edit {parameterId, value}\` (the id is in the result of
   \`parameter.create\` and in \`parameters.list\`; \`name\` renames). It must
   evaluate without errors and change the bounding box; then
   \`history.undo\`.

Rules:

- One parameter per independent design intent; derive the rest with
  expressions instead of duplicating numbers.
- Expressions use \`+ - * / ( )\` and other parameter names; lengths in mm,
  angles in degrees.
- A parameter that is still used cannot be deleted (\`conflict\` lists the
  usages); renaming rewrites every expression that names it.
- Tell the user which parameters to change for which effect.
`,
  'printable-part': `---
id: printable-part
name: Design a printable part
description: Workflow from a plain-language request to a checked, editable, printable part, with the acceptance rules to meet before saying it is done.
version: 1
scope: built-in
tags: [workflow, printing, modeling]
---

# Design a printable part

Use this for any "make me a …" request. The result must be a normal,
editable History (sketches and features), never a mesh.

## 1. Understand the request

- List the dimensions the user gave. For every missing dimension pick a
  sensible printable default (walls 2 mm, fillets 1–3 mm, clearances
  0.2–0.4 mm for fits, M3 holes 3.4 mm) and say which defaults you chose.
- Never invent real-world sizes of products you do not know exactly (a
  board's hole spacing, a connector's position). Ask, or state the value
  as an assumption the user should check. Known references (for example
  Raspberry Pi 5: 85 × 56 mm board, M2.5 holes 58 × 49 mm apart, 3.5 mm
  from the short edge) may be used but must be named in the answer.
- Read \`skills_read api-quickstart\` once if you have not used the API in
  this session.

## 2. Model with a plan

1. \`document.get\` and \`bodies.list\`: build on what exists, do not wipe the
   user's work. Never call \`project.new\`/\`project.open\` unless asked.
2. Base shape: a sketch on \`XY\` (\`feature.create\` kind \`sketch\` with
   \`profiles\`) and an \`extrude\`. Prefer parameters for the sizes the user
   will want to change (see skill \`parametric-part\`).
3. Details in printing order: shell / pockets (\`extrude\` \`cut\`), holes
   (\`hole\` or circles cut), ribs, then fillets and chamfers last.
4. After every write check the result's \`errors\`; on \`featureFailed\` read
   \`details\` and the hint, change the parameters, do not retry blindly.
5. Name features and bodies so the History reads well ("Base", "Vents").

## 3. Look at it

- \`view_render\` (iso, shadedEdges) after the main shape and after the
  details; \`view_inspect\` once at the end (iso, front, top, right).
- Compare the picture with the request: openings on the right side,
  nothing floating, walls where they should be. Fix what is wrong.

## 4. Check printability (acceptance rules)

Run \`print.analyze\` (or \`view_render\` with \`overlay: ["printFindings"]\`).
The part is done only when:

- every body is valid (\`brepValid\`, \`watertight\`) and there are no feature
  errors;
- no \`error\` findings remain; overhang warnings are either fixed (chamfer
  45°, flip the part with \`print.orient\`) or explained to the user;
- walls are at least the nozzle-safe minimum (0.8 mm default \`minWallMm\`);
- holes and pins meet \`minHoleMm\`/\`minPinMm\`;
- the part fits the build volume if the user named a printer;
- the bounding box matches the requested outer size (\`bodies.list\` bbox).

## 5. Report

Say what you built (main sizes, bodies), the defaults you assumed, the
printability result (findings left and why), and how to change the key
sizes (parameter names). Keep it short.
`,
};
