//! Offline model-package verification and hardware-aware Photolab execution planning.
//!
//! This module never downloads artifacts and never changes a requested quality profile.
//! Hardware adaptation is limited to equivalent backends and resource scheduling.

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::{hash::ObjectHash, photolab::AlignmentQualityProfile};

const MIB: u64 = 1024 * 1024;
const GIB: u64 = 1024 * MIB;

/// Compute backend encoded by a packaged model artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ModelBackend {
    Cpu,
    Vulkan,
    Cuda,
}

/// On-disk representation of an offline model artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ModelArtifactFormat {
    Onnx,
    SafeTensors,
    Ncnn,
    Native,
}

/// Redistribution and attribution data pinned with an artifact.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelLicenseMetadata {
    pub spdx_expression: String,
    pub copyright_notice: String,
    pub license_file: String,
    pub redistribution_approved: bool,
}

/// Immutable upstream provenance retained for audits, never used for runtime downloads.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelSourceMetadata {
    pub repository: String,
    pub revision: String,
    pub artifact_name: String,
}

/// One backend-specific artifact in a signed offline model package.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelArtifactManifest {
    pub schema_version: u32,
    pub id: String,
    pub version: String,
    pub backend: ModelBackend,
    pub format: ModelArtifactFormat,
    pub sha256: ObjectHash,
    pub byte_size: u64,
    /// Shared by artifacts that implement the same model and numerical quality contract.
    pub quality_fingerprint: ObjectHash,
    pub license: ModelLicenseMetadata,
    pub source: ModelSourceMetadata,
}

/// Signature envelope generated by the offline package build pipeline.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ManifestSignature {
    pub algorithm: String,
    pub signer_key_id: String,
    pub signature: String,
}

/// Manifest plus detached signature. It is not trusted until verified locally.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SignedModelManifest {
    pub manifest: ModelArtifactManifest,
    pub signature: ManifestSignature,
}

/// Capability supplied by the native signature implementation.
///
/// Implementations must use only locally provisioned trust roots. Network-backed key lookup is
/// outside this domain contract.
pub trait OfflineManifestSignatureVerifier {
    fn verify(&self, canonical_manifest: &[u8], signature: &ManifestSignature) -> bool;
}

/// Type-safe proof that manifest metadata and its detached signature were verified.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VerifiedModelManifest {
    signed: SignedModelManifest,
    canonical_manifest_sha256: ObjectHash,
}

impl VerifiedModelManifest {
    #[must_use]
    pub fn manifest(&self) -> &ModelArtifactManifest {
        &self.signed.manifest
    }

    #[must_use]
    pub fn signature(&self) -> &ManifestSignature {
        &self.signed.signature
    }

    #[must_use]
    pub fn canonical_manifest_sha256(&self) -> &ObjectHash {
        &self.canonical_manifest_sha256
    }
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum ManifestVerificationError {
    #[error("model manifest schema version must be non-zero")]
    InvalidSchemaVersion,
    #[error("model manifest field '{0}' must not be empty")]
    EmptyField(&'static str),
    #[error("model artifact byte size must be non-zero")]
    EmptyArtifact,
    #[error("model manifest contains an invalid SHA-256 value in '{0}'")]
    InvalidSha256(&'static str),
    #[error("model license is not approved for redistribution")]
    RedistributionNotApproved,
    #[error("failed to serialize model manifest for signature verification: {0}")]
    Serialization(String),
    #[error("model manifest signature is invalid or its signer is not trusted")]
    InvalidSignature,
}

/// Verifies a signed manifest using local trust material and returns an unforgeable wrapper.
pub fn verify_signed_manifest(
    signed: SignedModelManifest,
    verifier: &impl OfflineManifestSignatureVerifier,
) -> Result<VerifiedModelManifest, ManifestVerificationError> {
    validate_manifest_metadata(&signed)?;
    let canonical_manifest = serde_json::to_vec(&signed.manifest)
        .map_err(|error| ManifestVerificationError::Serialization(error.to_string()))?;
    if !verifier.verify(&canonical_manifest, &signed.signature) {
        return Err(ManifestVerificationError::InvalidSignature);
    }

    Ok(VerifiedModelManifest {
        canonical_manifest_sha256: ObjectHash::of_bytes(&canonical_manifest),
        signed,
    })
}

fn validate_manifest_metadata(
    signed: &SignedModelManifest,
) -> Result<(), ManifestVerificationError> {
    let manifest = &signed.manifest;
    if manifest.schema_version == 0 {
        return Err(ManifestVerificationError::InvalidSchemaVersion);
    }
    for (name, value) in [
        ("id", manifest.id.as_str()),
        ("version", manifest.version.as_str()),
        (
            "license.spdxExpression",
            manifest.license.spdx_expression.as_str(),
        ),
        (
            "license.licenseFile",
            manifest.license.license_file.as_str(),
        ),
        ("source.repository", manifest.source.repository.as_str()),
        ("source.revision", manifest.source.revision.as_str()),
        (
            "source.artifactName",
            manifest.source.artifact_name.as_str(),
        ),
        ("signature.algorithm", signed.signature.algorithm.as_str()),
        (
            "signature.signerKeyId",
            signed.signature.signer_key_id.as_str(),
        ),
        ("signature.signature", signed.signature.signature.as_str()),
    ] {
        if value.trim().is_empty() {
            return Err(ManifestVerificationError::EmptyField(name));
        }
    }
    if manifest.byte_size == 0 {
        return Err(ManifestVerificationError::EmptyArtifact);
    }
    if !is_sha256(&manifest.sha256) {
        return Err(ManifestVerificationError::InvalidSha256("sha256"));
    }
    if !is_sha256(&manifest.quality_fingerprint) {
        return Err(ManifestVerificationError::InvalidSha256(
            "qualityFingerprint",
        ));
    }
    if !manifest.license.redistribution_approved {
        return Err(ManifestVerificationError::RedistributionNotApproved);
    }
    Ok(())
}

fn is_sha256(hash: &ObjectHash) -> bool {
    hash.as_str().len() == 64 && hash.as_str().bytes().all(|byte| byte.is_ascii_hexdigit())
}

/// Stable key joining an installation record to its signed manifest.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelArtifactKey {
    pub id: String,
    pub version: String,
    pub backend: ModelBackend,
    pub format: ModelArtifactFormat,
}

impl From<&ModelArtifactManifest> for ModelArtifactKey {
    fn from(manifest: &ModelArtifactManifest) -> Self {
        Self {
            id: manifest.id.clone(),
            version: manifest.version.clone(),
            backend: manifest.backend,
            format: manifest.format,
        }
    }
}

/// Local installer state. Only `Verified` records are eligible for execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum LocalVerificationState {
    Unverified,
    Verified,
    Rejected,
}

/// Observation produced by the local package installer after reading an artifact.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LocalModelInstallation {
    pub key: ModelArtifactKey,
    /// Package-relative path. Resolution and path canonicalization belong to the installer.
    pub relative_path: String,
    pub observed_sha256: ObjectHash,
    pub observed_byte_size: u64,
    pub state: LocalVerificationState,
}

/// A logical model and exact quality contract required by the selected profile.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RequiredOfflineModel {
    pub id: String,
    pub version: String,
    pub quality_fingerprint: ObjectHash,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum HostOperatingSystem {
    Windows,
    Linux,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CpuCapabilities {
    pub physical_cores: u16,
    pub logical_cores: u16,
    pub supports_avx2: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VulkanCapabilities {
    pub api_version: String,
    pub device_name: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CudaComputeCapability {
    pub major: u8,
    pub minor: u8,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CudaCapabilities {
    pub device_name: String,
    pub compute_capability: CudaComputeCapability,
}

/// Snapshot taken before a run is queued. Planning performs no hardware probing itself.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HardwareCapabilities {
    pub operating_system: HostOperatingSystem,
    pub ram_bytes: u64,
    pub dedicated_vram_bytes: Option<u64>,
    pub cpu: CpuCapabilities,
    pub vulkan: Option<VulkanCapabilities>,
    pub cuda: Option<CudaCapabilities>,
}

/// Hardware-sensitive limits for one backend. They do not alter model or profile quality.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BackendResourcePlan {
    pub backend: ModelBackend,
    pub tile_edge_pixels: u32,
    pub batch_size: u16,
    pub max_concurrency: u16,
    pub cpu_threads_per_worker: u16,
}

/// One locally verified artifact in an ordered, quality-equivalent fallback chain.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PlannedModelArtifact {
    pub backend: ModelBackend,
    pub format: ModelArtifactFormat,
    pub relative_path: String,
    pub sha256: ObjectHash,
    pub byte_size: u64,
}

/// Exact logical model plus backend alternatives. Every artifact shares its quality fingerprint.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PlannedOfflineModel {
    pub requirement: RequiredOfflineModel,
    pub primary: PlannedModelArtifact,
    pub fallbacks: Vec<PlannedModelArtifact>,
}

/// Immutable plan persisted with a Photolab job.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OfflineModelExecutionPlan {
    pub schema_version: u32,
    pub profile: AlignmentQualityProfile,
    pub offline_only: bool,
    pub models: Vec<PlannedOfflineModel>,
    pub resources: Vec<BackendResourcePlan>,
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum OfflineModelPlanningError {
    #[error("quality profile requires at least one offline model")]
    EmptyRequirements,
    #[error("required model id and version must not be empty")]
    InvalidRequirement,
    #[error("required model '{id}' version '{version}' has no signed manifest")]
    MissingManifest { id: String, version: String },
    #[error("required model '{id}' version '{version}' is not installed locally")]
    MissingModel { id: String, version: String },
    #[error("installed model '{id}' version '{version}' has not been locally verified")]
    UnverifiedModel { id: String, version: String },
    #[error("installed model '{id}' version '{version}' has an unexpected SHA-256 hash")]
    HashMismatch { id: String, version: String },
    #[error("installed model '{id}' version '{version}' has an unexpected byte size")]
    ByteSizeMismatch { id: String, version: String },
    #[error("model '{id}' version '{version}' does not match the required quality fingerprint")]
    QualityMismatch { id: String, version: String },
    #[error(
        "required model '{id}' version '{version}' has no verified artifact for this hardware"
    )]
    NoCompatibleBackend { id: String, version: String },
}

/// Builds a fully offline plan without substituting a different model or quality fingerprint.
pub fn plan_offline_models(
    profile: AlignmentQualityProfile,
    requirements: &[RequiredOfflineModel],
    manifests: &[VerifiedModelManifest],
    installations: &[LocalModelInstallation],
    hardware: &HardwareCapabilities,
) -> Result<OfflineModelExecutionPlan, OfflineModelPlanningError> {
    if requirements.is_empty() {
        return Err(OfflineModelPlanningError::EmptyRequirements);
    }

    let backend_order = available_backends(hardware);
    let mut planned_models = Vec::with_capacity(requirements.len());
    for requirement in requirements {
        if requirement.id.trim().is_empty() || requirement.version.trim().is_empty() {
            return Err(OfflineModelPlanningError::InvalidRequirement);
        }
        if !is_sha256(&requirement.quality_fingerprint) {
            return Err(OfflineModelPlanningError::QualityMismatch {
                id: requirement.id.clone(),
                version: requirement.version.clone(),
            });
        }

        planned_models.push(plan_required_model(
            requirement,
            manifests,
            installations,
            &backend_order,
        )?);
    }

    let resources = backend_order
        .iter()
        .copied()
        .map(|backend| resource_plan(backend, hardware))
        .collect();

    Ok(OfflineModelExecutionPlan {
        schema_version: 1,
        profile,
        offline_only: true,
        models: planned_models,
        resources,
    })
}

fn plan_required_model(
    requirement: &RequiredOfflineModel,
    manifests: &[VerifiedModelManifest],
    installations: &[LocalModelInstallation],
    backend_order: &[ModelBackend],
) -> Result<PlannedOfflineModel, OfflineModelPlanningError> {
    let logical_manifests: Vec<_> = manifests
        .iter()
        .filter(|verified| {
            let manifest = verified.manifest();
            manifest.id == requirement.id && manifest.version == requirement.version
        })
        .collect();
    if logical_manifests.is_empty() {
        return Err(OfflineModelPlanningError::MissingManifest {
            id: requirement.id.clone(),
            version: requirement.version.clone(),
        });
    }
    if logical_manifests
        .iter()
        .all(|verified| verified.manifest().quality_fingerprint != requirement.quality_fingerprint)
    {
        return Err(OfflineModelPlanningError::QualityMismatch {
            id: requirement.id.clone(),
            version: requirement.version.clone(),
        });
    }

    let mut verified_artifacts = Vec::new();
    let mut first_validation_error = None;
    for backend in backend_order {
        for verified in logical_manifests.iter().filter(|verified| {
            let manifest = verified.manifest();
            manifest.backend == *backend
                && manifest.quality_fingerprint == requirement.quality_fingerprint
        }) {
            match validate_installation(verified.manifest(), installations) {
                Ok(artifact) => verified_artifacts.push(artifact),
                Err(error) => {
                    if first_validation_error.is_none() {
                        first_validation_error = Some(error);
                    }
                }
            }
        }
    }

    let Some(primary) = verified_artifacts.first().cloned() else {
        if let Some(error) = first_validation_error {
            return Err(error);
        }
        return Err(OfflineModelPlanningError::NoCompatibleBackend {
            id: requirement.id.clone(),
            version: requirement.version.clone(),
        });
    };

    Ok(PlannedOfflineModel {
        requirement: requirement.clone(),
        primary,
        fallbacks: verified_artifacts.into_iter().skip(1).collect(),
    })
}

fn validate_installation(
    manifest: &ModelArtifactManifest,
    installations: &[LocalModelInstallation],
) -> Result<PlannedModelArtifact, OfflineModelPlanningError> {
    let expected_key = ModelArtifactKey::from(manifest);
    let Some(installation) = installations
        .iter()
        .find(|installation| installation.key == expected_key)
    else {
        return Err(OfflineModelPlanningError::MissingModel {
            id: manifest.id.clone(),
            version: manifest.version.clone(),
        });
    };
    if installation.state != LocalVerificationState::Verified {
        return Err(OfflineModelPlanningError::UnverifiedModel {
            id: manifest.id.clone(),
            version: manifest.version.clone(),
        });
    }
    if installation.observed_sha256 != manifest.sha256 {
        return Err(OfflineModelPlanningError::HashMismatch {
            id: manifest.id.clone(),
            version: manifest.version.clone(),
        });
    }
    if installation.observed_byte_size != manifest.byte_size {
        return Err(OfflineModelPlanningError::ByteSizeMismatch {
            id: manifest.id.clone(),
            version: manifest.version.clone(),
        });
    }

    Ok(PlannedModelArtifact {
        backend: manifest.backend,
        format: manifest.format,
        relative_path: installation.relative_path.clone(),
        sha256: manifest.sha256.clone(),
        byte_size: manifest.byte_size,
    })
}

fn available_backends(hardware: &HardwareCapabilities) -> Vec<ModelBackend> {
    let mut backends = Vec::with_capacity(3);
    if hardware.cuda.is_some() {
        backends.push(ModelBackend::Cuda);
    }
    if hardware.vulkan.is_some() {
        backends.push(ModelBackend::Vulkan);
    }
    backends.push(ModelBackend::Cpu);
    backends
}

fn resource_plan(backend: ModelBackend, hardware: &HardwareCapabilities) -> BackendResourcePlan {
    let usable_bytes = match backend {
        ModelBackend::Cpu => hardware.ram_bytes,
        ModelBackend::Vulkan | ModelBackend::Cuda => hardware
            .dedicated_vram_bytes
            .unwrap_or(hardware.ram_bytes / 4),
    };
    let (tile_edge_pixels, batch_size, memory_concurrency) = if usable_bytes >= 16 * GIB {
        (4_096, 8, 8)
    } else if usable_bytes >= 8 * GIB {
        (3_072, 4, 4)
    } else if usable_bytes >= 4 * GIB {
        (2_048, 2, 2)
    } else {
        (1_024, 1, 1)
    };
    let logical_cores = hardware.cpu.logical_cores.max(1);
    let max_concurrency = memory_concurrency.min(logical_cores).max(1);
    let cpu_threads_per_worker = (logical_cores / max_concurrency).max(1);

    BackendResourcePlan {
        backend,
        tile_edge_pixels,
        batch_size,
        max_concurrency,
        cpu_threads_per_worker,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TestVerifier;

    impl OfflineManifestSignatureVerifier for TestVerifier {
        fn verify(&self, canonical_manifest: &[u8], signature: &ManifestSignature) -> bool {
            signature.signature == ObjectHash::of_bytes(canonical_manifest).0
        }
    }

    fn hash(seed: &[u8]) -> ObjectHash {
        ObjectHash::of_bytes(seed)
    }

    fn signed_manifest(
        id: &str,
        backend: ModelBackend,
        format: ModelArtifactFormat,
        artifact_bytes: &[u8],
        quality_fingerprint: &ObjectHash,
    ) -> SignedModelManifest {
        let manifest = ModelArtifactManifest {
            schema_version: 1,
            id: id.to_owned(),
            version: "1.0.0".to_owned(),
            backend,
            format,
            sha256: hash(artifact_bytes),
            byte_size: artifact_bytes.len() as u64,
            quality_fingerprint: quality_fingerprint.clone(),
            license: ModelLicenseMetadata {
                spdx_expression: "Apache-2.0".to_owned(),
                copyright_notice: "Test fixture".to_owned(),
                license_file: "LICENSES/test.txt".to_owned(),
                redistribution_approved: true,
            },
            source: ModelSourceMetadata {
                repository: "https://example.invalid/model".to_owned(),
                revision: "0123456789abcdef".to_owned(),
                artifact_name: "model.onnx".to_owned(),
            },
        };
        let canonical = serde_json::to_vec(&manifest).expect("fixture manifest must serialize");
        SignedModelManifest {
            manifest,
            signature: ManifestSignature {
                algorithm: "test-sha256".to_owned(),
                signer_key_id: "offline-test-key".to_owned(),
                signature: ObjectHash::of_bytes(&canonical).0,
            },
        }
    }

    fn verified_manifest(
        id: &str,
        backend: ModelBackend,
        format: ModelArtifactFormat,
        artifact_bytes: &[u8],
        quality_fingerprint: &ObjectHash,
    ) -> VerifiedModelManifest {
        verify_signed_manifest(
            signed_manifest(id, backend, format, artifact_bytes, quality_fingerprint),
            &TestVerifier,
        )
        .expect("fixture signature must verify")
    }

    fn installation(manifest: &VerifiedModelManifest) -> LocalModelInstallation {
        let manifest = manifest.manifest();
        LocalModelInstallation {
            key: ModelArtifactKey::from(manifest),
            relative_path: format!("models/{}/artifact", manifest.id),
            observed_sha256: manifest.sha256.clone(),
            observed_byte_size: manifest.byte_size,
            state: LocalVerificationState::Verified,
        }
    }

    fn requirement(id: &str, quality_fingerprint: &ObjectHash) -> RequiredOfflineModel {
        RequiredOfflineModel {
            id: id.to_owned(),
            version: "1.0.0".to_owned(),
            quality_fingerprint: quality_fingerprint.clone(),
        }
    }

    fn hardware(
        ram_gib: u64,
        vram_gib: Option<u64>,
        vulkan: bool,
        cuda: bool,
    ) -> HardwareCapabilities {
        HardwareCapabilities {
            operating_system: HostOperatingSystem::Linux,
            ram_bytes: ram_gib * GIB,
            dedicated_vram_bytes: vram_gib.map(|value| value * GIB),
            cpu: CpuCapabilities {
                physical_cores: 8,
                logical_cores: 16,
                supports_avx2: true,
            },
            vulkan: vulkan.then(|| VulkanCapabilities {
                api_version: "1.3".to_owned(),
                device_name: "Test Vulkan GPU".to_owned(),
            }),
            cuda: cuda.then(|| CudaCapabilities {
                device_name: "Test CUDA GPU".to_owned(),
                compute_capability: CudaComputeCapability { major: 8, minor: 6 },
            }),
        }
    }

    #[test]
    fn signed_manifest_requires_valid_local_signature() {
        let quality = hash(b"quality");
        let mut signed = signed_manifest(
            "feature-model",
            ModelBackend::Cpu,
            ModelArtifactFormat::Onnx,
            b"weights",
            &quality,
        );
        signed.signature.signature = "invalid".to_owned();

        assert_eq!(
            verify_signed_manifest(signed, &TestVerifier),
            Err(ManifestVerificationError::InvalidSignature)
        );
    }

    #[test]
    fn rejects_missing_required_model_without_network_fallback() {
        let quality = hash(b"quality");
        let manifest = verified_manifest(
            "feature-model",
            ModelBackend::Cpu,
            ModelArtifactFormat::Onnx,
            b"weights",
            &quality,
        );

        let result = plan_offline_models(
            AlignmentQualityProfile::QualityHybrid,
            &[requirement("feature-model", &quality)],
            &[manifest],
            &[],
            &hardware(16, None, false, false),
        );

        assert_eq!(
            result,
            Err(OfflineModelPlanningError::MissingModel {
                id: "feature-model".to_owned(),
                version: "1.0.0".to_owned(),
            })
        );
    }

    #[test]
    fn rejects_hash_mismatched_local_artifact() {
        let quality = hash(b"quality");
        let manifest = verified_manifest(
            "feature-model",
            ModelBackend::Cpu,
            ModelArtifactFormat::Onnx,
            b"weights",
            &quality,
        );
        let mut installed = installation(&manifest);
        installed.observed_sha256 = hash(b"tampered");

        let result = plan_offline_models(
            AlignmentQualityProfile::QualityHybrid,
            &[requirement("feature-model", &quality)],
            &[manifest],
            &[installed],
            &hardware(16, None, false, false),
        );

        assert_eq!(
            result,
            Err(OfflineModelPlanningError::HashMismatch {
                id: "feature-model".to_owned(),
                version: "1.0.0".to_owned(),
            })
        );
    }

    #[test]
    fn cuda_primary_falls_back_only_to_quality_equivalent_artifacts() {
        let quality = hash(b"same-quality");
        let cuda = verified_manifest(
            "feature-model",
            ModelBackend::Cuda,
            ModelArtifactFormat::Native,
            b"cuda-weights",
            &quality,
        );
        let vulkan = verified_manifest(
            "feature-model",
            ModelBackend::Vulkan,
            ModelArtifactFormat::Ncnn,
            b"vulkan-weights",
            &quality,
        );
        let cpu = verified_manifest(
            "feature-model",
            ModelBackend::Cpu,
            ModelArtifactFormat::Onnx,
            b"cpu-weights",
            &quality,
        );
        let installations = vec![
            installation(&cuda),
            installation(&vulkan),
            installation(&cpu),
        ];

        let plan = plan_offline_models(
            AlignmentQualityProfile::MaximumRobustness,
            &[requirement("feature-model", &quality)],
            &[cuda, vulkan, cpu],
            &installations,
            &hardware(32, Some(12), true, true),
        )
        .expect("all exact model variants are locally verified");

        assert_eq!(plan.profile, AlignmentQualityProfile::MaximumRobustness);
        assert!(plan.offline_only);
        assert_eq!(plan.models[0].primary.backend, ModelBackend::Cuda);
        assert_eq!(plan.models[0].fallbacks.len(), 2);
        assert_eq!(plan.models[0].fallbacks[0].backend, ModelBackend::Vulkan);
        assert_eq!(plan.models[0].fallbacks[1].backend, ModelBackend::Cpu);
        assert_eq!(plan.models[0].requirement.quality_fingerprint, quality);
    }

    #[test]
    fn low_memory_changes_scheduling_but_not_quality_or_model_selection() {
        let quality = hash(b"fixed-quality");
        let cpu = verified_manifest(
            "feature-model",
            ModelBackend::Cpu,
            ModelArtifactFormat::Onnx,
            b"cpu-weights",
            &quality,
        );
        let installed = installation(&cpu);
        let requirements = [requirement("feature-model", &quality)];
        let manifests = [cpu];
        let installations = [installed];

        let low = plan_offline_models(
            AlignmentQualityProfile::MaximumRobustness,
            &requirements,
            &manifests,
            &installations,
            &hardware(4, None, false, false),
        )
        .expect("CPU artifact supports constrained hardware");
        let high = plan_offline_models(
            AlignmentQualityProfile::MaximumRobustness,
            &requirements,
            &manifests,
            &installations,
            &hardware(32, None, false, false),
        )
        .expect("same CPU artifact supports high-end hardware");

        assert_eq!(low.profile, high.profile);
        assert_eq!(low.models, high.models);
        assert_eq!(low.resources[0].tile_edge_pixels, 2_048);
        assert_eq!(low.resources[0].batch_size, 2);
        assert_eq!(high.resources[0].tile_edge_pixels, 4_096);
        assert_eq!(high.resources[0].batch_size, 8);
        assert!(high.resources[0].max_concurrency > low.resources[0].max_concurrency);
    }

    #[test]
    fn incompatible_quality_fingerprint_is_never_used_as_fallback() {
        let required_quality = hash(b"required-quality");
        let reduced_quality = hash(b"reduced-quality");
        let manifest = verified_manifest(
            "feature-model",
            ModelBackend::Cpu,
            ModelArtifactFormat::Onnx,
            b"smaller-weights",
            &reduced_quality,
        );
        let installed = installation(&manifest);

        let result = plan_offline_models(
            AlignmentQualityProfile::MaximumRobustness,
            &[requirement("feature-model", &required_quality)],
            &[manifest],
            &[installed],
            &hardware(4, None, false, false),
        );

        assert_eq!(
            result,
            Err(OfflineModelPlanningError::QualityMismatch {
                id: "feature-model".to_owned(),
                version: "1.0.0".to_owned(),
            })
        );
    }
}
