/**
 * WP-G2 input to the Builder-owned generated command table.
 *
 * Values are stable public row ids. Keys in PHOTOLAB_RPC_TO_COMMAND_ROW are
 * today's private renderer RPCs; cancellation and cleanup RPCs deliberately
 * point at the operation row that owns that lifecycle.
 */
export const AUTOMATION_COMMAND_ROW_IDS = [
  'photolab.alignment.merge.candidates',
  'photolab.alignment.merge.list',
  'photolab.alignment.merge.plan',
  'photolab.alignment.merge.preflight',
  'photolab.alignment.merge.start',
  'photolab.alignment.resolve',
  'photolab.alignment.settings.update',
  'photolab.alignment.start',
  'photolab.batch.start',
  'photolab.calibration_groups.initial_calibration.set',
  'photolab.calibration_groups.intrinsics.update',
  'photolab.calibration_groups.list',
  'photolab.capture.capabilities',
  'photolab.capture.image.prepare',
  'photolab.capture.scale.evaluate',
  'photolab.capture.video.prepare',
  'photolab.capture_groups.confirm',
  'photolab.capture_groups.create',
  'photolab.capture_groups.draft',
  'photolab.capture_groups.list',
  'photolab.capture_groups.merge',
  'photolab.crs.discover',
  'photolab.crs.freeze',
  'photolab.entities.move',
  'photolab.entities.rename',
  'photolab.entities.visibility.set',
  'photolab.gcp.aligned_cameras',
  'photolab.gcp.calibration_report',
  'photolab.gcp.images',
  'photolab.gcp.import.commit',
  'photolab.gcp.import.preview',
  'photolab.gcp.list',
  'photolab.gcp.local_estimate.compute',
  'photolab.gcp.observation.edit',
  'photolab.gcp.observation.upsert',
  'photolab.gcp.observation.upsert_assisted',
  'photolab.gcp.optimization.latest',
  'photolab.gcp.optimization.list',
  'photolab.gcp.optimization.snapshot',
  'photolab.gcp.optimization.start',
  'photolab.hardware.probe',
  'photolab.image_masks.edit',
  'photolab.image_masks.list',
  'photolab.images.himmelcap.inspect',
  'photolab.images.import.commit',
  'photolab.images.import.inspect',
  'photolab.images.list',
  'photolab.images.quality.list',
  'photolab.images.quality.start',
  'photolab.images.remove',
  'photolab.jobs.cancel',
  'photolab.jobs.list',
  'photolab.jobs.resume',
  'photolab.jobs.status',
  'photolab.processing_sets.create',
  'photolab.processing_sets.list',
  'photolab.products.export',
  'photolab.products.list',
  'photolab.products.resolve_inputs',
  'photolab.products.start',
  'photolab.project.autosave',
  'photolab.project.close',
  'photolab.project.create',
  'photolab.project.diagnostics',
  'photolab.project.open',
  'photolab.project.recent.list',
  'photolab.project.recent.remove',
  'photolab.project.reopen_without_recovery',
  'photolab.project.save',
  'photolab.project.save_as',
  'photolab.project.snapshot',
  'photolab.project.untitled.cleanup',
  'photolab.report.export',
  'photolab.report.survey_data',
] as const;

export type AutomationCommandRowId = (typeof AUTOMATION_COMMAND_ROW_IDS)[number];

export const SHARED_COMMAND_ROW_IDS = ['io.import'] as const;

export const PHOTOLAB_RPC_TO_COMMAND_ROW: Readonly<Record<string, AutomationCommandRowId>> = {
  'photolab.alignment.resolve': 'photolab.alignment.resolve',
  'photolab.alignmentMerge.preflight': 'photolab.alignment.merge.preflight',
  'photolab.capture.cancel': 'photolab.capture.video.prepare',
  'photolab.capture.capabilities': 'photolab.capture.capabilities',
  'photolab.capture.image.prepare': 'photolab.capture.image.prepare',
  'photolab.capture.scale.evaluate': 'photolab.capture.scale.evaluate',
  'photolab.capture.video.prepare': 'photolab.capture.video.prepare',
  'photolab.crs.cancel': 'photolab.crs.freeze',
  'photolab.crs.discover': 'photolab.crs.discover',
  'photolab.crs.freeze': 'photolab.crs.freeze',
  'photolab.gcp.alignedCameras': 'photolab.gcp.aligned_cameras',
  'photolab.gcp.calibrationReport': 'photolab.gcp.calibration_report',
  // S-06c product rows in the shared tree context menu (surface contextMenu).
  'photolab.gcp.images': 'photolab.gcp.images',
  'photolab.images.remove': 'photolab.images.remove',
  'photolab.gcp.cancel': 'photolab.gcp.import.commit',
  'photolab.gcp.commit': 'photolab.gcp.import.commit',
  'photolab.gcp.list': 'photolab.gcp.list',
  'photolab.gcp.localEstimate.compute': 'photolab.gcp.local_estimate.compute',
  'photolab.gcp.observation.edit': 'photolab.gcp.observation.edit',
  'photolab.gcp.observation.upsert': 'photolab.gcp.observation.upsert',
  'photolab.gcp.observation.upsertAssisted': 'photolab.gcp.observation.upsert_assisted',
  'photolab.gcp.optimization.latest': 'photolab.gcp.optimization.latest',
  'photolab.gcp.optimization.list': 'photolab.gcp.optimization.list',
  'photolab.gcp.optimization.snapshot': 'photolab.gcp.optimization.snapshot',
  'photolab.gcp.preview': 'photolab.gcp.import.preview',
  'photolab.hardware.probe': 'photolab.hardware.probe',
  'photolab.himmelcap.cancel': 'photolab.images.himmelcap.inspect',
  'photolab.himmelcap.inspect': 'photolab.images.himmelcap.inspect',
  'photolab.himmelcap.release': 'photolab.images.himmelcap.inspect',
  'photolab.images.commit': 'photolab.images.import.commit',
  'photolab.images.commit.cancel': 'photolab.images.import.commit',
  'photolab.images.inspect': 'photolab.images.import.inspect',
  'photolab.images.inspect.cancel': 'photolab.images.import.inspect',
  'photolab.images.list': 'photolab.images.list',
  'photolab.images.quality.list': 'photolab.images.quality.list',
  'photolab.jobs.cancel': 'photolab.jobs.cancel',
  'photolab.jobs.list': 'photolab.jobs.list',
  'photolab.jobs.resume': 'photolab.jobs.resume',
  'photolab.jobs.status': 'photolab.jobs.status',
  'photolab.jobs.startAlignment': 'photolab.alignment.start',
  'photolab.jobs.startAlignmentMerge': 'photolab.alignment.merge.start',
  'photolab.jobs.startBatch': 'photolab.batch.start',
  'photolab.jobs.startGcpOptimization': 'photolab.gcp.optimization.start',
  'photolab.jobs.startImageQuality': 'photolab.images.quality.start',
  'photolab.jobs.startProduct': 'photolab.products.start',
  'photolab.products.list': 'photolab.products.list',
  'photolab.products.resolveInputs': 'photolab.products.resolve_inputs',
  'photolab.project.alignmentMerge.candidates': 'photolab.alignment.merge.candidates',
  'photolab.project.alignmentMerge.create': 'photolab.alignment.merge.plan',
  'photolab.project.alignmentMerge.list': 'photolab.alignment.merge.list',
  'photolab.project.autosave': 'photolab.project.autosave',
  'photolab.project.archive.cancel': 'photolab.project.save_as',
  'photolab.project.calibrationGroup.list': 'photolab.calibration_groups.list',
  'photolab.project.calibrationGroup.setInitialCalibration':
    'photolab.calibration_groups.initial_calibration.set',
  'photolab.project.calibrationGroup.updateIntrinsics':
    'photolab.calibration_groups.intrinsics.update',
  'photolab.project.captureGroup.confirm': 'photolab.capture_groups.confirm',
  'photolab.project.captureGroup.create': 'photolab.capture_groups.create',
  'photolab.project.captureGroup.duplicateAsDraft': 'photolab.capture_groups.draft',
  'photolab.project.captureGroup.list': 'photolab.capture_groups.list',
  'photolab.project.captureGroup.mergeProposals': 'photolab.capture_groups.merge',
  'photolab.project.diagnostics': 'photolab.project.diagnostics',
  'photolab.project.entity.move': 'photolab.entities.move',
  'photolab.project.entity.rename': 'photolab.entities.rename',
  'photolab.project.entity.visibility': 'photolab.entities.visibility.set',
  'photolab.project.imageMask.edit': 'photolab.image_masks.edit',
  'photolab.project.imageMask.cancel': 'photolab.image_masks.edit',
  'photolab.project.imageMask.list': 'photolab.image_masks.list',
  'photolab.project.images.remove': 'photolab.images.remove',
  'photolab.project.journal.finish': 'photolab.alignment.settings.update',
  'photolab.project.journal.start': 'photolab.alignment.settings.update',
  'photolab.project.processingSet.create': 'photolab.processing_sets.create',
  'photolab.project.processingSet.list': 'photolab.processing_sets.list',
  'photolab.project.snapshot': 'photolab.project.snapshot',
  'photolab.report.surveyData': 'photolab.report.survey_data',
};

export const RIBBON_COMMAND_TO_COMMAND_ROW = {
  'project.new': 'photolab.project.create',
  'project.open': 'photolab.project.open',
  'project.recent': 'photolab.project.recent.list',
  'project.save': 'photolab.project.save',
  'project.saveAs': 'photolab.project.save_as',
  'images.import.files': 'photolab.images.import.inspect',
  'images.import.folder': 'photolab.images.import.inspect',
  'images.import.videoFrames': 'photolab.capture.video.prepare',
  'data.import.external': 'io.import',
  'images.quality': 'photolab.images.quality.list',
  'reference.transform': 'photolab.crs.discover',
  'reference.gcp.import': 'photolab.gcp.import.preview',
  'alignment.run': 'photolab.alignment.start',
  'alignment.define': 'photolab.processing_sets.create',
  'alignment.optimize': 'photolab.gcp.optimization.start',
  'alignment.merge': 'photolab.alignment.merge.plan',
  'alignment.groups': 'photolab.capture_groups.list',
  'alignment.report': 'photolab.report.survey_data',
  'products.depth': 'photolab.products.start',
  'products.dense': 'photolab.products.start',
  'products.dem': 'photolab.products.start',
  'products.ortho': 'photolab.products.start',
  'products.mesh': 'photolab.products.start',
  'products.splat': 'photolab.products.start',
  'batch.queue': 'photolab.jobs.list',
} as const;

/** Ribbon acts that only reveal or configure a local view, with no product operation. */
export const RIBBON_VIEW_LOCAL_ALLOWLIST = {
  'automation.agent': 'Shows or hides the shared Agent workspace; the visibility is view-local.',
  'images.metadata': 'Opens a panel over the already-loaded image snapshot; it changes no state.',
  'batch.configure': 'Opens the local recipe editor; only an explicit batch start is an operation.',
} as const;
