#!/usr/bin/env node
/**
 * Embeds the built-in assistant skills (`assembler/agent-skills/builtin/<id>/SKILL.md`,
 * the source of truth) into `renderer/src/interface/assistant/builtinSkills.generated.ts`,
 * so the app, the headless CLI and the tests ship the same read-only bytes.
 *
 *   node apps/assembler/scripts/generate-skills.mjs          write the file
 *   node apps/assembler/scripts/generate-skills.mjs --check  exit 1 if it is stale
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(here, '..');
const repoRoot = resolve(appRoot, '..', '..');
const sourceDir = join(repoRoot, 'assembler', 'agent-skills', 'builtin');
const target = join(
  appRoot,
  'renderer',
  'src',
  'interface',
  'assistant',
  'builtinSkills.generated.ts',
);

export function generate() {
  const ids = readdirSync(sourceDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(join(sourceDir, entry.name, 'SKILL.md')))
    .map((entry) => entry.name)
    .sort();
  const entries = ids.map((id) => {
    const text = readFileSync(join(sourceDir, id, 'SKILL.md'), 'utf8').replace(/\r\n/g, '\n');
    // A template literal keeps the Markdown readable and is left alone by prettier.
    const literal = text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
    return `  '${id}': \`${literal}\`,`;
  });
  return [
    '// Generated by apps/assembler/scripts/generate-skills.mjs from',
    '// assembler/agent-skills/builtin/*/SKILL.md — do not edit; run the script.',
    '',
    '/** Built-in assistant skills: id → SKILL.md text (frontmatter + Markdown body). */',
    'export const BUILTIN_SKILL_FILES: Readonly<Record<string, string>> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

const output = generate();
if (process.argv.includes('--check')) {
  const current = existsSync(target) ? readFileSync(target, 'utf8').replace(/\r\n/g, '\n') : '';
  if (current !== output) {
    console.error(`${target} is stale: run node apps/assembler/scripts/generate-skills.mjs`);
    process.exit(1);
  }
} else {
  writeFileSync(target, output, 'utf8');
  console.log(`wrote ${target}`);
}
