//! Generated by `scripts/generate-hardware-quirks.mjs`; do not edit manually.

#[allow(unused_imports)]
use crate::quirks::{
    HardwareQuirk, HardwareQuirkActions, HardwareQuirkMatch, HardwareQuirkVersion,
};

/// Reviewed hardware quirks generated from the canonical JSON registry.
#[must_use]
pub fn generated_quirks() -> Vec<HardwareQuirk> {
    Vec::new()
}
