#!/usr/bin/env python3
"""Generate the HimmelCAD Python automation SDK from its protocol schema."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import tempfile
from pathlib import Path
from typing import Any


GENERATOR_VERSION = "1.0.0"
REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCHEMA = REPOSITORY_ROOT / "schemas/automation/himmelcad-automation-v1.schema.json"
DEFAULT_OUTPUT = REPOSITORY_ROOT / "sdk/python"


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def snake(name: str) -> str:
    value = re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()
    return {"filter": "entity_filter", "schema": "schema"}.get(value, value)


def descriptor(node: dict[str, Any]) -> Any:
    if "$ref" in node:
        return ["model", node["$ref"].rsplit("/", 1)[-1]]
    if "const" in node:
        return ["scalar", type(node["const"]).__name__]
    kind = node.get("type")
    if isinstance(kind, list) and "null" in kind:
        concrete = dict(node)
        concrete["type"] = next(item for item in kind if item != "null")
        return ["nullable", descriptor(concrete)]
    if kind == "array":
        return ["tuple", descriptor(node.get("items", {}))]
    if kind == "object":
        return ["mapping"]
    return ["scalar", {"integer": "int", "number": "float", "boolean": "bool", "string": "str"}.get(kind, "Any")]


def annotation(node: dict[str, Any]) -> str:
    desc = descriptor(node)
    if desc[0] == "nullable":
        concrete = dict(node)
        concrete["type"] = next(item for item in node["type"] if item != "null")
        return f"{annotation(concrete)} | None"
    if desc[0] == "model":
        return desc[1]
    if desc[0] == "tuple":
        inner = annotation(node.get("items", {}))
        return f"tuple[{inner}, ...]"
    if desc[0] == "mapping":
        return "Mapping[str, Any]"
    return desc[1]


def model_source(schema: dict[str, Any]) -> str:
    definitions = schema["$defs"]
    blocks: list[str] = []
    specs: dict[str, Any] = {}
    variants: dict[str, Any] = {}
    for name, definition in definitions.items():
        if definition.get("type") != "object" or "properties" not in definition:
            continue
        properties = definition["properties"]
        required = set(definition.get("required", []))
        ordered = [key for key in properties if key in required] + [key for key in properties if key not in required]
        aliases = {snake(key): key for key in ordered}
        fields = []
        field_specs = {}
        for key in ordered:
            py_name = snake(key)
            field_type = annotation(properties[key])
            optional = key not in required
            sensitive = bool(properties[key].get("writeOnly", False))
            if sensitive:
                declaration = f"    {py_name}: {field_type}{' | None' if optional else ''} = dataclass_field(repr=False{', default=None' if optional else ''})"
            else:
                declaration = f"    {py_name}: {field_type}{' | None = None' if optional else ''}"
            fields.append(declaration)
            field_specs[py_name] = {
                "descriptor": descriptor(properties[key]),
                "required": not optional,
                "const": properties[key].get("const", None),
                "hasConst": "const" in properties[key],
                "enum": properties[key].get("enum"),
                "minimum": properties[key].get("minimum"),
                "maximum": properties[key].get("maximum"),
                "minItems": properties[key].get("minItems"),
                "maxItems": properties[key].get("maxItems"),
                "minLength": properties[key].get("minLength"),
                "pattern": properties[key].get("pattern"),
                "uniqueItems": properties[key].get("uniqueItems", False),
                "exclusiveMinimum": properties[key].get("exclusiveMinimum"),
                "nullable": isinstance(properties[key].get("type"), list) and "null" in properties[key]["type"],
                "writeOnly": sensitive,
            }
        body = "\n".join(fields) if fields else "    pass"
        blocks.append(
            f"@dataclass(frozen=True, slots=True)\nclass {name}(WireModel):\n{body}\n"
            f"    _ALIASES: ClassVar[Mapping[str, str]] = MappingProxyType({aliases!r})\n"
        )
        specs[name] = field_specs
        if "x-variants" in definition:
            variants[name] = {
                "discriminator": snake(definition["x-discriminator"]),
                "variants": {key: [snake(item) for item in value] for key, value in definition["x-variants"].items()},
            }

    return '''# Generated by scripts/generate-automation-sdk.py; do not edit.
from __future__ import annotations

from dataclasses import dataclass, field as dataclass_field, fields
import re
from types import MappingProxyType
from typing import Any, ClassVar, Mapping, TypeVar, cast

_T = TypeVar("_T", bound="WireModel")


def _freeze(value: Any) -> Any:
    if isinstance(value, Mapping):
        return MappingProxyType({str(key): _freeze(item) for key, item in value.items()})
    if isinstance(value, (list, tuple)):
        return tuple(_freeze(item) for item in value)
    return value


def _wire(value: Any) -> Any:
    if isinstance(value, WireModel):
        return value.to_dict()
    if isinstance(value, Mapping):
        return {key: _wire(item) for key, item in value.items()}
    if isinstance(value, tuple):
        return [_wire(item) for item in value]
    return value


class WireModel:
    _ALIASES: ClassVar[Mapping[str, str]] = MappingProxyType({})

    def __post_init__(self) -> None:
        for field in fields(self):
            object.__setattr__(self, field.name, _freeze(getattr(self, field.name)))
        _validate(self)

    @classmethod
    def from_dict(cls: type[_T], value: Mapping[str, Any]) -> _T:
        if not isinstance(value, Mapping):
            raise TypeError(f"{cls.__name__} requires a mapping")
        reverse = {wire: python for python, wire in cls._ALIASES.items()}
        unknown = set(value).difference(reverse)
        if unknown:
            raise ValueError(f"unknown {cls.__name__} fields: {sorted(unknown)!r}")
        spec = _MODEL_SPECS[cls.__name__]
        missing = [cls._ALIASES[name] for name, item in spec.items() if item["required"] and cls._ALIASES[name] not in value]
        if missing:
            raise ValueError(f"missing {cls.__name__} fields: {missing!r}")
        variant = _VARIANT_SPECS.get(cls.__name__)
        if variant is not None:
            discriminator_wire = cls._ALIASES[variant["discriminator"]]
            discriminator = value.get(discriminator_wire)
            selected = set(variant["variants"].get(discriminator, ()))
            variant_fields = set().union(*map(set, variant["variants"].values()))
            missing_variant = sorted(cls._ALIASES[name] for name in selected if cls._ALIASES[name] not in value)
            forbidden_variant = sorted(cls._ALIASES[name] for name in variant_fields - selected if cls._ALIASES[name] in value)
            if not selected or missing_variant or forbidden_variant:
                raise ValueError(f"invalid {cls.__name__} variant fields; missing={missing_variant!r}, forbidden={forbidden_variant!r}")
        kwargs = {
            reverse[key]: _decode(spec[reverse[key]]["descriptor"], item)
            for key, item in value.items()
        }
        return cls(**kwargs)

    def to_dict(self) -> dict[str, Any]:
        variant = _VARIANT_SPECS.get(self.__class__.__name__)
        variant_required: set[str] = set()
        if variant is not None:
            variant_required = set(variant["variants"].get(getattr(self, variant["discriminator"]), ()))
        return {
            self._ALIASES[field.name]: _wire(getattr(self, field.name))
            for field in fields(self)
            if getattr(self, field.name) is not None
            or _MODEL_SPECS[self.__class__.__name__][field.name]["required"]
            or field.name in variant_required
        }


''' + "\n\n".join(blocks) + f'''

_MODEL_TYPES: Mapping[str, type[WireModel]] = MappingProxyType({{
    name: value for name, value in globals().copy().items()
    if isinstance(value, type) and issubclass(value, WireModel) and value is not WireModel
}})
_MODEL_SPECS: Mapping[str, Any] = MappingProxyType({specs!r})
_VARIANT_SPECS: Mapping[str, Any] = MappingProxyType({variants!r})


def _decode(desc: list[Any], value: Any) -> Any:
    if desc[0] == "nullable":
        return None if value is None else _decode(desc[1], value)
    if value is None:
        raise TypeError("null is not allowed")
    if desc[0] == "model":
        return _MODEL_TYPES[desc[1]].from_dict(value)
    if desc[0] == "tuple":
        if not isinstance(value, (list, tuple)):
            raise TypeError("expected an array")
        return tuple(_decode(desc[1], item) for item in value)
    if desc[0] == "mapping":
        if not isinstance(value, Mapping):
            raise TypeError("expected an object")
        return _freeze(value)
    expected = {{"str": str, "int": int, "float": (int, float), "bool": bool, "Any": object}}[desc[1]]
    if not isinstance(value, expected) or (desc[1] in {{"int", "float"}} and isinstance(value, bool)):
        raise TypeError(f"expected {{desc[1]}}")
    return float(value) if desc[1] == "float" else value


def _validate(value: WireModel) -> None:
    spec = _MODEL_SPECS[value.__class__.__name__]
    for name, constraints in spec.items():
        item = getattr(value, name)
        if item is None:
            if constraints["required"] and not constraints["nullable"]:
                raise ValueError(f"{{name}} may not be null")
            continue
        _assert_type(constraints["descriptor"], item, name)
        if constraints["hasConst"] and item != constraints["const"]:
            raise ValueError(f"{{name}} must equal {{constraints['const']!r}}")
        enum = constraints["enum"]
        if enum is not None and item not in enum:
            raise ValueError(f"{{name}} must be one of {{enum!r}}")
        minimum = constraints["minimum"]
        maximum = constraints["maximum"]
        if minimum is not None and item < minimum:
            raise ValueError(f"{{name}} is below its minimum")
        if maximum is not None and item > maximum:
            raise ValueError(f"{{name}} exceeds its maximum")
        min_items = constraints["minItems"]
        max_items = constraints["maxItems"]
        if min_items is not None and len(item) < min_items:
            raise ValueError(f"{{name}} has too few items")
        if max_items is not None and len(item) > max_items:
            raise ValueError(f"{{name}} has too many items")
        min_length = constraints["minLength"]
        if min_length is not None and len(item) < min_length:
            raise ValueError(f"{{name}} is too short")
        pattern = constraints["pattern"]
        if pattern is not None and re.fullmatch(pattern, item) is None:
            raise ValueError(f"{{name}} does not match its pattern")
        if constraints["uniqueItems"] and any(item[index] in item[:index] for index in range(len(item))):
            raise ValueError(f"{{name}} must contain unique items")
        exclusive_minimum = constraints["exclusiveMinimum"]
        if exclusive_minimum is not None and item <= exclusive_minimum:
            raise ValueError(f"{{name}} must be greater than its exclusive minimum")
    variant = _VARIANT_SPECS.get(value.__class__.__name__)
    if variant is not None:
        discriminator = getattr(value, variant["discriminator"])
        required = set(variant["variants"].get(discriminator, ()))
        if not required:
            raise ValueError(f"unknown {{variant['discriminator']}} variant {{discriminator!r}}")
        variant_fields = set().union(*map(set, variant["variants"].values()))
        missing = sorted(name for name in required if getattr(value, name) is None and not _MODEL_SPECS[value.__class__.__name__][name]["nullable"])
        forbidden = sorted(name for name in variant_fields - required if getattr(value, name) is not None)
        if missing or forbidden:
            raise ValueError(f"invalid {{discriminator}} variant fields; missing={{missing!r}}, forbidden={{forbidden!r}}")


def _assert_type(desc: list[Any], value: Any, path: str) -> None:
    if desc[0] == "nullable":
        if value is not None:
            _assert_type(desc[1], value, path)
        return
    if desc[0] == "model":
        if not isinstance(value, _MODEL_TYPES[desc[1]]):
            raise TypeError(f"{{path}} must be {{desc[1]}}")
        return
    if desc[0] == "tuple":
        if not isinstance(value, tuple):
            raise TypeError(f"{{path}} must be an immutable tuple")
        for index, item in enumerate(value):
            _assert_type(desc[1], item, f"{{path}}[{{index}}]")
        return
    if desc[0] == "mapping":
        if not isinstance(value, Mapping):
            raise TypeError(f"{{path}} must be a mapping")
        return
    expected = {{"str": str, "int": int, "float": (int, float), "bool": bool, "Any": object}}[desc[1]]
    if not isinstance(value, expected) or (desc[1] in {{"int", "float"}} and isinstance(value, bool)):
        raise TypeError(f"{{path}} must be {{desc[1]}}")


def to_wire(value: Any) -> Any:
    """Convert generated immutable models into JSON-compatible values."""
    return _wire(value)
'''


ERRORS_TEMPLATE = '''# Generated by scripts/generate-automation-sdk.py; do not edit.
from __future__ import annotations

from enum import Enum
from types import MappingProxyType
from typing import Any, Mapping


class ErrorCode(str, Enum):
{members}
    UNKNOWN = "unknown"


class HimmelcadError(RuntimeError):
    def __init__(self, *, raw_code: str, message: str, retryable: bool = False, details: Mapping[str, Any] | None = None) -> None:
        try:
            self.code = ErrorCode(raw_code)
        except ValueError:
            self.code = ErrorCode.UNKNOWN
        self.raw_code = raw_code
        self.message = message
        self.retryable = retryable
        self.details = MappingProxyType(dict(details or {{}}))
        super().__init__(f"{{raw_code}}: {{message}}")


class ProtocolError(HimmelcadError):
    pass


class TransportError(HimmelcadError):
    pass


class ValidationError(HimmelcadError):
    pass


class GenerationChangedError(HimmelcadError):
    pass


class LeaseError(HimmelcadError):
    pass


def error_from_payload(payload: Mapping[str, Any]) -> HimmelcadError:
    raw_code = str(payload.get("code", "internal"))
    cls: type[HimmelcadError]
    if raw_code == "generationChanged":
        cls = GenerationChangedError
    elif raw_code.startswith("lease") or raw_code == "hashMismatch":
        cls = LeaseError
    elif raw_code in {{"invalidRequest", "invalidCursor", "pageLimitExceeded", "byteLimitExceeded"}}:
        cls = ValidationError
    else:
        cls = ProtocolError
    return cls(
        raw_code=raw_code,
        message=str(payload.get("message", "HimmelCAD request failed")),
        retryable=bool(payload.get("retryable", False)),
        details=payload.get("details") if isinstance(payload.get("details"), Mapping) else None,
    )
'''


LEASES_TEMPLATE = '''# Generated by scripts/generate-automation-sdk.py; do not edit.
from __future__ import annotations

import base64
import hashlib
from typing import TYPE_CHECKING, Any

from .errors import LeaseError
from .models import BulkLeaseDescriptor

if TYPE_CHECKING:
    from .client import AsyncHimmelcadClient, HimmelcadClient

_DTYPES = {
    "uint8": "u1", "int8": "i1", "uint16": "u2", "int16": "i2",
    "uint32": "u4", "int32": "i4", "uint64": "u8", "int64": "i8",
    "float32": "f4", "float64": "f8", "bytes": "u1",
}
_ELEMENT_BYTES = {
    "bytes": 1, "uint8": 1, "int8": 1, "uint16": 2, "int16": 2,
    "uint32": 4, "int32": 4, "uint64": 8, "int64": 8, "float32": 4, "float64": 8,
}
_MAX_SHAPE_ELEMENTS = __MAX_SHAPE_ELEMENTS__


def _validate_descriptor(descriptor: BulkLeaseDescriptor) -> None:
    elements = 1
    for dimension in descriptor.shape:
        elements *= dimension
        if elements > _MAX_SHAPE_ELEMENTS:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk lease shape exceeds maxShapeElements")
    expected_bytes = elements * _ELEMENT_BYTES[descriptor.element_type]
    if expected_bytes != descriptor.byte_length:
        raise LeaseError(raw_code="leaseRangeInvalid", message="bulk byteLength does not match elementType and shape")
    if descriptor.remaining_read_budget < descriptor.byte_length:
        raise LeaseError(raw_code="leaseBudgetExhausted", message="bulk lease cannot be read completely within its budget")


class BulkLease:
    def __init__(self, client: HimmelcadClient, descriptor: BulkLeaseDescriptor) -> None:
        _validate_descriptor(descriptor)
        self.client = client
        self.descriptor = descriptor
        self.remaining_read_budget = descriptor.remaining_read_budget
        self.released = False

    def __enter__(self) -> BulkLease:
        return self

    def __exit__(self, *_: object) -> None:
        self.release()

    def read(self, offset: int, length: int) -> bytes:
        self._check(offset, length)
        result = self.client._bulk_read(self.descriptor, offset, length)
        data = base64.b64decode(result.data, validate=True)
        if len(data) != result.byte_length or result.offset != offset:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk response range does not match its request")
        self.remaining_read_budget = result.remaining_read_budget
        return data

    def read_all(self) -> bytes:
        chunks = []
        for offset in range(0, self.descriptor.byte_length, self.descriptor.max_readable_range):
            chunks.append(self.read(offset, min(self.descriptor.max_readable_range, self.descriptor.byte_length - offset)))
        data = b"".join(chunks)
        if hashlib.sha256(data).hexdigest() != self.descriptor.content_hash:
            raise LeaseError(raw_code="hashMismatch", message="bulk payload hash does not match its descriptor")
        return data

    def numpy(self) -> Any:
        try:
            import numpy as np
        except ImportError as error:
            raise RuntimeError("install himmelcad[numpy] to use BulkLease.numpy()") from error
        prefix = {"little": "<", "big": ">", "notApplicable": "|"}[self.descriptor.endianness]
        array = np.frombuffer(self.read_all(), dtype=np.dtype(prefix + _DTYPES[self.descriptor.element_type]))
        if self.descriptor.shape:
            expected = 1
            for dimension in self.descriptor.shape:
                expected *= dimension
            if expected != array.size:
                raise LeaseError(raw_code="leaseRangeInvalid", message="lease shape does not match payload size")
            array = array.reshape(self.descriptor.shape)
        array.flags.writeable = False
        return array

    def release(self) -> None:
        if not self.released:
            self.client._bulk_release(self.descriptor)
            self.released = True

    def _check(self, offset: int, length: int) -> None:
        if self.released:
            raise LeaseError(raw_code="leaseRevoked", message="bulk lease was already released")
        if offset < 0 or length <= 0 or offset + length > self.descriptor.byte_length:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk read is outside the described payload")
        if length > self.descriptor.max_readable_range:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk read exceeds maxReadableRange")
        if length > self.remaining_read_budget:
            raise LeaseError(raw_code="leaseBudgetExhausted", message="bulk read exceeds remainingReadBudget")


class AsyncBulkLease:
    def __init__(self, client: AsyncHimmelcadClient, descriptor: BulkLeaseDescriptor) -> None:
        _validate_descriptor(descriptor)
        self.client = client
        self.descriptor = descriptor
        self.remaining_read_budget = descriptor.remaining_read_budget
        self.released = False

    async def __aenter__(self) -> AsyncBulkLease:
        return self

    async def __aexit__(self, *_: object) -> None:
        await self.release()

    async def read(self, offset: int, length: int) -> bytes:
        self._check(offset, length)
        result = await self.client._bulk_read(self.descriptor, offset, length)
        data = base64.b64decode(result.data, validate=True)
        if len(data) != result.byte_length or result.offset != offset:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk response range does not match its request")
        self.remaining_read_budget = result.remaining_read_budget
        return data

    async def read_all(self) -> bytes:
        chunks = []
        for offset in range(0, self.descriptor.byte_length, self.descriptor.max_readable_range):
            chunks.append(await self.read(offset, min(self.descriptor.max_readable_range, self.descriptor.byte_length - offset)))
        data = b"".join(chunks)
        if hashlib.sha256(data).hexdigest() != self.descriptor.content_hash:
            raise LeaseError(raw_code="hashMismatch", message="bulk payload hash does not match its descriptor")
        return data

    async def numpy(self) -> Any:
        try:
            import numpy as np
        except ImportError as error:
            raise RuntimeError("install himmelcad[numpy] to use AsyncBulkLease.numpy()") from error
        prefix = {"little": "<", "big": ">", "notApplicable": "|"}[self.descriptor.endianness]
        array = np.frombuffer(await self.read_all(), dtype=np.dtype(prefix + _DTYPES[self.descriptor.element_type]))
        if self.descriptor.shape:
            expected = 1
            for dimension in self.descriptor.shape:
                expected *= dimension
            if expected != array.size:
                raise LeaseError(raw_code="leaseRangeInvalid", message="lease shape does not match payload size")
            array = array.reshape(self.descriptor.shape)
        array.flags.writeable = False
        return array

    async def release(self) -> None:
        if not self.released:
            await self.client._bulk_release(self.descriptor)
            self.released = True

    def _check(self, offset: int, length: int) -> None:
        if self.released:
            raise LeaseError(raw_code="leaseRevoked", message="bulk lease was already released")
        if offset < 0 or length <= 0 or offset + length > self.descriptor.byte_length:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk read is outside the described payload")
        if length > self.descriptor.max_readable_range:
            raise LeaseError(raw_code="leaseRangeInvalid", message="bulk read exceeds maxReadableRange")
        if length > self.remaining_read_budget:
            raise LeaseError(raw_code="leaseBudgetExhausted", message="bulk read exceeds remainingReadBudget")
'''


CLIENT_TEMPLATE = '''# Generated by scripts/generate-automation-sdk.py; do not edit.
from __future__ import annotations

import base64
import math
import uuid
from collections.abc import AsyncIterator, Iterable, Iterator, Mapping
from types import MappingProxyType
from typing import Any, Protocol

from .errors import GenerationChangedError, ProtocolError, ValidationError, error_from_payload
from .leases import AsyncBulkLease, BulkLease
from .models import (
    BulkLeaseDescriptor, BulkReadResult, BulkReleaseResult, CanonicalCommandTransaction, CanonicalEntity,
    CanonicalEntityEdit, CanonicalEntityMutation,
    CasDescription, CommandCancelResult, CommandStatus, CommandValidationPlan, EntityPage,
    EntityVersionRef, JournalPage, PropertyId, PropertyQueryResult, ProtocolNegotiationResponse, ScreenshotResultV1,
    ViewStateV2, WireModel, to_wire,
)

LIMITS = MappingProxyType({limits})
METHOD_CAPABILITIES = MappingProxyType({method_capabilities})
APP_METHOD_CAPABILITIES = MappingProxyType({app_method_capabilities})


class Transport(Protocol):
    def request(self, method: str, params: Mapping[str, Any]) -> Mapping[str, Any]: ...


class AsyncTransport(Protocol):
    async def request(self, method: str, params: Mapping[str, Any]) -> Mapping[str, Any]: ...


def _params(value: WireModel | Mapping[str, Any] | None) -> Mapping[str, Any]:
    return to_wire(value or {{}})


def _raise_direct_error(response: Mapping[str, Any]) -> None:
    payload = response.get("error")
    if isinstance(payload, Mapping):
        raise error_from_payload(payload)


def _app_payload(response: Mapping[str, Any], expected_kind: str, request_id: str) -> Any:
    _raise_direct_error(response)
    if response.get("schemaId") != "hcad.app-protocol@1" or response.get("requestId") != request_id:
        raise ProtocolError(raw_code="invalidRequest", message="app.protocol response correlation does not match its request")
    body = response.get("response")
    if not isinstance(body, Mapping):
        raise ProtocolError(raw_code="invalidRequest", message="app.protocol response envelope is missing response")
    kind = body.get("kind")
    payload = body.get("payload", {{}})
    if kind == "error" and isinstance(payload, Mapping):
        raise error_from_payload(payload)
    if kind != expected_kind:
        raise ProtocolError(raw_code="invalidRequest", message=f"expected {{expected_kind}}, received {{kind!r}}")
    return payload


class CanonicalTransactionBuilder:
    def __init__(self, command_id: str | None = None) -> None:
        self.command_id = command_id or str(uuid.uuid4())
        self._mutations: list[CanonicalEntityMutation] = []

    def add(self, mutation: CanonicalEntityMutation) -> CanonicalTransactionBuilder:
        self._mutations.append(mutation)
        return self

    def create(self, entity: CanonicalEntity) -> CanonicalTransactionBuilder:
        return self.add(CanonicalEntityMutation(operation="create", entity=entity))

    def update(self, expected: EntityVersionRef, edits: Iterable[CanonicalEntityEdit]) -> CanonicalTransactionBuilder:
        return self.add(CanonicalEntityMutation(operation="update", expected=expected, edits=tuple(edits)))

    def delete(self, expected: EntityVersionRef) -> CanonicalTransactionBuilder:
        return self.add(CanonicalEntityMutation(operation="delete", expected=expected))

    def restore(self, expected: EntityVersionRef, snapshot: CanonicalEntity) -> CanonicalTransactionBuilder:
        return self.add(CanonicalEntityMutation(operation="restore", expected=expected, snapshot=snapshot))

    def build(self) -> CanonicalCommandTransaction:
        if not self._mutations:
            raise ValidationError(raw_code="invalidRequest", message="a canonical transaction requires at least one mutation")
        return CanonicalCommandTransaction(command_id=self.command_id, mutations=tuple(self._mutations))


class HimmelcadClient:
    def __init__(self, transport: Transport) -> None:
        self.transport = transport
        self.session: ProtocolNegotiationResponse | None = None

    def negotiate(self, client_name: str = "himmelcad-python", *, required_capabilities: Iterable[str] = (), optional_capabilities: Iterable[str] = ()) -> ProtocolNegotiationResponse:
        required = tuple(required_capabilities)
        value = self._call("app.negotiate", {{"clientName": client_name, "supportedVersions": [1], "requiredCapabilities": list(required), "optionalCapabilities": list(optional_capabilities)}})
        self.session = ProtocolNegotiationResponse.from_dict(value)
        missing = sorted(set(required).difference(self.session.capabilities))
        if self.session.selected_version != 1 or missing:
            self.session = None
            raise ProtocolError(raw_code="protocolMismatch" if not missing else "missingCapability", message=f"negotiation rejected selectedVersion or capabilities; missing={{missing!r}}")
        return self.session

    def entities_page(self, *, cursor: str | None = None, generation: int | None = None, limit: int = LIMITS["maxPageItems"], byte_limit: int = LIMITS["maxPageBytes"], entity_filter: Mapping[str, Any] | None = None) -> EntityPage:
        if limit <= 0 or limit > LIMITS["maxPageItems"] or byte_limit <= 0 or byte_limit > LIMITS["maxPageBytes"]:
            raise ValidationError(raw_code="pageLimitExceeded", message="invalid entity page bounds")
        params = {{"limit": limit, "byteLimit": byte_limit}}
        if cursor is not None: params["cursor"] = cursor
        if generation is not None: params["generation"] = generation
        if entity_filter is not None: params["filter"] = dict(entity_filter)
        return EntityPage.from_dict(self._call("automation.entities.page", params))

    def iter_entity_pages(self, *, max_pages: int = 10_000, **kwargs: Any) -> Iterator[EntityPage]:
        if max_pages <= 0: raise ValidationError(raw_code="pageLimitExceeded", message="max_pages must be positive")
        cursor = kwargs.pop("cursor", None)
        generation = kwargs.pop("generation", None)
        seen = set() if cursor is None else {{cursor}}
        for _ in range(max_pages):
            page = self.entities_page(cursor=cursor, generation=generation, **kwargs)
            limit = int(kwargs.get("limit", LIMITS["maxPageItems"]))
            byte_limit = int(kwargs.get("byte_limit", LIMITS["maxPageBytes"]))
            if len(page.items) > limit or page.returned_bytes > byte_limit:
                raise ProtocolError(raw_code="pageLimitExceeded", message="entity page exceeds requested bounds")
            if generation is None: generation = page.generation
            elif page.generation != generation:
                raise GenerationChangedError(raw_code="generationChanged", message="entity generation changed while paging")
            yield page
            cursor = page.next_cursor
            if cursor is None: return
            if cursor in seen: raise ProtocolError(raw_code="invalidCursor", message="entity cursor did not advance")
            seen.add(cursor)
        raise ProtocolError(raw_code="pageLimitExceeded", message="entity pagination exceeded max_pages")

    def iter_entities(self, **kwargs: Any) -> Iterator[Any]:
        for page in self.iter_entity_pages(**kwargs):
            yield from page.items

    def iter_property_pages(self, entities: Iterable[EntityVersionRef], properties: Iterable[PropertyId]) -> Iterator[PropertyQueryResult]:
        entity_list = list(entities)
        if not entity_list: raise ValidationError(raw_code="invalidRequest", message="property queries require at least one entity")
        property_list = list(properties)
        size = LIMITS["maxPropertySelectionItems"]
        for index in range(0, len(entity_list), size):
            yield PropertyQueryResult.from_dict(self._app("queryProperties", {{"schemaId": "hcad.property-query-request@1", "entities": to_wire(tuple(entity_list[index:index + size])), "properties": to_wire(tuple(property_list))}}, "propertyQuery"))

    def iter_journal_pages(self, *, after_sequence: int = 0, limit: int = LIMITS["maxJournalPageItems"], max_pages: int = 10_000) -> Iterator[JournalPage]:
        if limit <= 0 or limit > LIMITS["maxJournalPageItems"] or max_pages <= 0: raise ValidationError(raw_code="pageLimitExceeded", message="invalid journal paging bounds")
        for _ in range(max_pages):
            page = JournalPage.from_dict(self._app("readJournal", {{"afterSequence": after_sequence, "limit": limit}}, "journalPage"))
            if page.after_sequence != after_sequence or len(page.entries) > limit:
                raise ProtocolError(raw_code="invalidCursor", message="journal page does not match requested bounds")
            yield page
            entries = page.entries
            if not page.has_more: return
            if not entries:
                raise ProtocolError(raw_code="invalidCursor", message="journal page reports hasMore without entries")
            advanced = int(entries[-1]["sequence"])
            if advanced <= after_sequence: raise ProtocolError(raw_code="invalidCursor", message="journal cursor did not advance")
            after_sequence = advanced
        raise ProtocolError(raw_code="pageLimitExceeded", message="journal pagination exceeded max_pages")

    def snapshot(self) -> Mapping[str, Any]:
        return self._app("readDocumentSnapshot", {{}}, "documentSnapshot")

    def read_property_schemas(self) -> tuple[Mapping[str, Any], ...]:
        schemas = self._app("readPropertySchemas", {{}}, "propertySchemas")
        if not isinstance(schemas, (list, tuple)): raise ProtocolError(raw_code="invalidRequest", message="propertySchemas payload is not an array")
        return tuple(MappingProxyType(dict(item)) for item in schemas)

    def compile_property_edit(self, request: Mapping[str, Any]) -> CanonicalCommandTransaction:
        return CanonicalCommandTransaction.from_dict(self._app("compilePropertyEdit", request, "compiledTransaction"))

    def validate(self, transaction: CanonicalCommandTransaction, *, accepted_loss_codes: Iterable[str] = ()) -> CommandValidationPlan:
        return CommandValidationPlan.from_dict(self._call("automation.commands.validate", {{"transaction": to_wire(transaction), "acceptedLossCodes": list(accepted_loss_codes)}}))

    def commit(self, transaction: CanonicalCommandTransaction, *, confirmation_grant: str | None = None) -> Mapping[str, Any]:
        extensions = None if confirmation_grant is None else {{"hcad.automation.confirmation@1": {{"grant": confirmation_grant}}}}
        return self._app("executeCanonicalTransaction", to_wire(transaction), "transactionAccepted", extensions=extensions)

    def command_status(self, operation_id: str) -> CommandStatus:
        return CommandStatus.from_dict(self._call("automation.commands.status", {{"operationId": operation_id}}))

    def cancel_command(self, operation_id: str) -> CommandCancelResult:
        return CommandCancelResult.from_dict(self._call("automation.commands.cancel", {{"operationId": operation_id}}))

    def cas_describe(self, content_hash: str) -> CasDescription:
        return CasDescription.from_dict(self._call("automation.cas.describe", {{"contentHash": content_hash}}))

    def get_view(self) -> ViewStateV2:
        return ViewStateV2.from_dict(self._call("view.state.get", {{}}))

    def set_view(self, state: ViewStateV2) -> ViewStateV2:
        return ViewStateV2.from_dict(self._call("view.state.set", to_wire(state)))

    def screenshot(self, request: WireModel | Mapping[str, Any]) -> bytes | BulkLease:
        request_wire = _params(request)
        result = ScreenshotResultV1.from_dict(self._call("view.screenshot", request_wire))
        mime = {{"png": "image/png", "jpeg": "image/jpeg", "webp": "image/webp"}}.get(request_wire.get("format"))
        expected_width = math.floor(float(request_wire.get("width", 0)) * float(request_wire.get("pixelRatio", 0)) + 0.5)
        expected_height = math.floor(float(request_wire.get("height", 0)) * float(request_wire.get("pixelRatio", 0)) + 0.5)
        if result.request_id != request_wire.get("requestId") or result.mime_type != mime or result.width != expected_width or result.height != expected_height:
            raise ProtocolError(raw_code="invalidRequest", message="screenshot result does not match request correlation or dimensions")
        if result.encoding == "base64" and result.data is not None:
            return base64.b64decode(result.data, validate=True)
        if result.encoding == "bulkLease" and result.lease is not None:
            return BulkLease(self, result.lease)
        raise ProtocolError(raw_code="invalidRequest", message="screenshot result lacks data for its encoding")

    def _bulk_read(self, descriptor: BulkLeaseDescriptor, offset: int, length: int) -> BulkReadResult:
        return BulkReadResult.from_dict(self._call("automation.bulk.read", {{"leaseId": descriptor.lease_id, "accessToken": descriptor.access_token, "offset": offset, "length": length}}))

    def _bulk_release(self, descriptor: BulkLeaseDescriptor) -> BulkReleaseResult:
        return BulkReleaseResult.from_dict(self._call("automation.bulk.release", {{"leaseId": descriptor.lease_id, "accessToken": descriptor.access_token}}))

    def _app(self, method: str, params: Mapping[str, Any], expected: str, *, extensions: Mapping[str, Any] | None = None) -> Any:
        self._require(APP_METHOD_CAPABILITIES[method])
        request_id = str(uuid.uuid4())
        envelope = {{"schemaId": "hcad.app-protocol@1", "requestId": request_id, "request": {{"method": method, "params": params}}}}
        if extensions is not None: envelope["extensions"] = dict(extensions)
        return _app_payload(self.transport.request("app.protocol", envelope), expected, request_id)

    def _call(self, method: str, params: Mapping[str, Any]) -> Mapping[str, Any]:
        capability = METHOD_CAPABILITIES.get(method)
        if capability is not None: self._require(capability)
        response = self.transport.request(method, params)
        _raise_direct_error(response)
        return response

    def _require(self, capability: str) -> None:
        if self.session is None or capability not in self.session.capabilities:
            raise ProtocolError(raw_code="missingCapability", message=f"negotiated session lacks {{capability}}")


class AsyncHimmelcadClient:
    def __init__(self, transport: AsyncTransport) -> None:
        self.transport = transport
        self.session: ProtocolNegotiationResponse | None = None

    async def negotiate(self, client_name: str = "himmelcad-python", *, required_capabilities: Iterable[str] = (), optional_capabilities: Iterable[str] = ()) -> ProtocolNegotiationResponse:
        required = tuple(required_capabilities)
        value = await self._call("app.negotiate", {{"clientName": client_name, "supportedVersions": [1], "requiredCapabilities": list(required), "optionalCapabilities": list(optional_capabilities)}})
        self.session = ProtocolNegotiationResponse.from_dict(value)
        missing = sorted(set(required).difference(self.session.capabilities))
        if self.session.selected_version != 1 or missing:
            self.session = None
            raise ProtocolError(raw_code="protocolMismatch" if not missing else "missingCapability", message=f"negotiation rejected selectedVersion or capabilities; missing={{missing!r}}")
        return self.session

    async def entities_page(self, *, cursor: str | None = None, generation: int | None = None, limit: int = LIMITS["maxPageItems"], byte_limit: int = LIMITS["maxPageBytes"], entity_filter: Mapping[str, Any] | None = None) -> EntityPage:
        if limit <= 0 or limit > LIMITS["maxPageItems"] or byte_limit <= 0 or byte_limit > LIMITS["maxPageBytes"]:
            raise ValidationError(raw_code="pageLimitExceeded", message="invalid entity page bounds")
        params = {{"limit": limit, "byteLimit": byte_limit}}
        if cursor is not None: params["cursor"] = cursor
        if generation is not None: params["generation"] = generation
        if entity_filter is not None: params["filter"] = dict(entity_filter)
        return EntityPage.from_dict(await self._call("automation.entities.page", params))

    async def iter_entity_pages(self, *, max_pages: int = 10_000, **kwargs: Any) -> AsyncIterator[EntityPage]:
        if max_pages <= 0: raise ValidationError(raw_code="pageLimitExceeded", message="max_pages must be positive")
        cursor = kwargs.pop("cursor", None)
        generation = kwargs.pop("generation", None)
        seen = set() if cursor is None else {{cursor}}
        for _ in range(max_pages):
            page = await self.entities_page(cursor=cursor, generation=generation, **kwargs)
            limit = int(kwargs.get("limit", LIMITS["maxPageItems"]))
            byte_limit = int(kwargs.get("byte_limit", LIMITS["maxPageBytes"]))
            if len(page.items) > limit or page.returned_bytes > byte_limit:
                raise ProtocolError(raw_code="pageLimitExceeded", message="entity page exceeds requested bounds")
            if generation is None: generation = page.generation
            elif page.generation != generation:
                raise GenerationChangedError(raw_code="generationChanged", message="entity generation changed while paging")
            yield page
            cursor = page.next_cursor
            if cursor is None: return
            if cursor in seen: raise ProtocolError(raw_code="invalidCursor", message="entity cursor did not advance")
            seen.add(cursor)
        raise ProtocolError(raw_code="pageLimitExceeded", message="entity pagination exceeded max_pages")

    async def iter_entities(self, **kwargs: Any) -> AsyncIterator[Any]:
        async for page in self.iter_entity_pages(**kwargs):
            for item in page.items: yield item

    async def iter_property_pages(self, entities: Iterable[EntityVersionRef], properties: Iterable[PropertyId]) -> AsyncIterator[PropertyQueryResult]:
        entity_list = list(entities)
        if not entity_list: raise ValidationError(raw_code="invalidRequest", message="property queries require at least one entity")
        property_list = list(properties)
        size = LIMITS["maxPropertySelectionItems"]
        for index in range(0, len(entity_list), size):
            yield PropertyQueryResult.from_dict(await self._app("queryProperties", {{"schemaId": "hcad.property-query-request@1", "entities": to_wire(tuple(entity_list[index:index + size])), "properties": to_wire(tuple(property_list))}}, "propertyQuery"))

    async def iter_journal_pages(self, *, after_sequence: int = 0, limit: int = LIMITS["maxJournalPageItems"], max_pages: int = 10_000) -> AsyncIterator[JournalPage]:
        if limit <= 0 or limit > LIMITS["maxJournalPageItems"] or max_pages <= 0: raise ValidationError(raw_code="pageLimitExceeded", message="invalid journal paging bounds")
        for _ in range(max_pages):
            page = JournalPage.from_dict(await self._app("readJournal", {{"afterSequence": after_sequence, "limit": limit}}, "journalPage"))
            if page.after_sequence != after_sequence or len(page.entries) > limit:
                raise ProtocolError(raw_code="invalidCursor", message="journal page does not match requested bounds")
            yield page
            entries = page.entries
            if not page.has_more: return
            if not entries:
                raise ProtocolError(raw_code="invalidCursor", message="journal page reports hasMore without entries")
            advanced = int(entries[-1]["sequence"])
            if advanced <= after_sequence: raise ProtocolError(raw_code="invalidCursor", message="journal cursor did not advance")
            after_sequence = advanced
        raise ProtocolError(raw_code="pageLimitExceeded", message="journal pagination exceeded max_pages")

    async def snapshot(self) -> Mapping[str, Any]:
        return await self._app("readDocumentSnapshot", {{}}, "documentSnapshot")

    async def read_property_schemas(self) -> tuple[Mapping[str, Any], ...]:
        schemas = await self._app("readPropertySchemas", {{}}, "propertySchemas")
        if not isinstance(schemas, (list, tuple)): raise ProtocolError(raw_code="invalidRequest", message="propertySchemas payload is not an array")
        return tuple(MappingProxyType(dict(item)) for item in schemas)

    async def compile_property_edit(self, request: Mapping[str, Any]) -> CanonicalCommandTransaction:
        return CanonicalCommandTransaction.from_dict(await self._app("compilePropertyEdit", request, "compiledTransaction"))

    async def validate(self, transaction: CanonicalCommandTransaction, *, accepted_loss_codes: Iterable[str] = ()) -> CommandValidationPlan:
        return CommandValidationPlan.from_dict(await self._call("automation.commands.validate", {{"transaction": to_wire(transaction), "acceptedLossCodes": list(accepted_loss_codes)}}))

    async def commit(self, transaction: CanonicalCommandTransaction, *, confirmation_grant: str | None = None) -> Mapping[str, Any]:
        extensions = None if confirmation_grant is None else {{"hcad.automation.confirmation@1": {{"grant": confirmation_grant}}}}
        return await self._app("executeCanonicalTransaction", to_wire(transaction), "transactionAccepted", extensions=extensions)

    async def command_status(self, operation_id: str) -> CommandStatus:
        return CommandStatus.from_dict(await self._call("automation.commands.status", {{"operationId": operation_id}}))

    async def cancel_command(self, operation_id: str) -> CommandCancelResult:
        return CommandCancelResult.from_dict(await self._call("automation.commands.cancel", {{"operationId": operation_id}}))

    async def cas_describe(self, content_hash: str) -> CasDescription:
        return CasDescription.from_dict(await self._call("automation.cas.describe", {{"contentHash": content_hash}}))

    async def get_view(self) -> ViewStateV2:
        return ViewStateV2.from_dict(await self._call("view.state.get", {{}}))

    async def set_view(self, state: ViewStateV2) -> ViewStateV2:
        return ViewStateV2.from_dict(await self._call("view.state.set", to_wire(state)))

    async def screenshot(self, request: WireModel | Mapping[str, Any]) -> bytes | AsyncBulkLease:
        request_wire = _params(request)
        result = ScreenshotResultV1.from_dict(await self._call("view.screenshot", request_wire))
        mime = {{"png": "image/png", "jpeg": "image/jpeg", "webp": "image/webp"}}.get(request_wire.get("format"))
        expected_width = math.floor(float(request_wire.get("width", 0)) * float(request_wire.get("pixelRatio", 0)) + 0.5)
        expected_height = math.floor(float(request_wire.get("height", 0)) * float(request_wire.get("pixelRatio", 0)) + 0.5)
        if result.request_id != request_wire.get("requestId") or result.mime_type != mime or result.width != expected_width or result.height != expected_height:
            raise ProtocolError(raw_code="invalidRequest", message="screenshot result does not match request correlation or dimensions")
        if result.encoding == "base64" and result.data is not None:
            return base64.b64decode(result.data, validate=True)
        if result.encoding == "bulkLease" and result.lease is not None:
            return AsyncBulkLease(self, result.lease)
        raise ProtocolError(raw_code="invalidRequest", message="screenshot result lacks data for its encoding")

    async def _bulk_read(self, descriptor: BulkLeaseDescriptor, offset: int, length: int) -> BulkReadResult:
        return BulkReadResult.from_dict(await self._call("automation.bulk.read", {{"leaseId": descriptor.lease_id, "accessToken": descriptor.access_token, "offset": offset, "length": length}}))

    async def _bulk_release(self, descriptor: BulkLeaseDescriptor) -> BulkReleaseResult:
        return BulkReleaseResult.from_dict(await self._call("automation.bulk.release", {{"leaseId": descriptor.lease_id, "accessToken": descriptor.access_token}}))

    async def _app(self, method: str, params: Mapping[str, Any], expected: str, *, extensions: Mapping[str, Any] | None = None) -> Any:
        self._require(APP_METHOD_CAPABILITIES[method])
        request_id = str(uuid.uuid4())
        envelope = {{"schemaId": "hcad.app-protocol@1", "requestId": request_id, "request": {{"method": method, "params": params}}}}
        if extensions is not None: envelope["extensions"] = dict(extensions)
        return _app_payload(await self.transport.request("app.protocol", envelope), expected, request_id)

    async def _call(self, method: str, params: Mapping[str, Any]) -> Mapping[str, Any]:
        capability = METHOD_CAPABILITIES.get(method)
        if capability is not None: self._require(capability)
        response = await self.transport.request(method, params)
        _raise_direct_error(response)
        return response

    def _require(self, capability: str) -> None:
        if self.session is None or capability not in self.session.capabilities:
            raise ProtocolError(raw_code="missingCapability", message=f"negotiated session lacks {{capability}}")
'''


INIT_TEMPLATE = '''# Generated by scripts/generate-automation-sdk.py; do not edit.
from .client import AsyncHimmelcadClient, CanonicalTransactionBuilder, HimmelcadClient
from .errors import ErrorCode, GenerationChangedError, HimmelcadError, LeaseError, ProtocolError, ValidationError
from .leases import AsyncBulkLease, BulkLease
from .models import *

__all__ = [
    "AsyncBulkLease", "AsyncHimmelcadClient", "BulkLease", "CanonicalTransactionBuilder",
    "ErrorCode", "GenerationChangedError", "HimmelcadClient", "HimmelcadError",
    "LeaseError", "ProtocolError", "ValidationError",
]
'''


PYPROJECT = '''[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "himmelcad"
version = "0.1.0"
description = "Generated sync and async SDK for HimmelCAD automation"
requires-python = ">=3.12"
license = { text = "Proprietary" }

[project.optional-dependencies]
numpy = ["numpy>=2"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
himmelcad = ["py.typed"]
'''


README_TEMPLATE = '''# HimmelCAD Python SDK

This package is generated from `schemas/automation/himmelcad-automation-v1.schema.json` and requires Python 3.12 or newer. Do not edit files under `src/himmelcad` by hand.

Both `HimmelcadClient` and `AsyncHimmelcadClient` use the existing HimmelCAD control planes. Document snapshots, journal pages, property operations and transaction commits travel through `app.protocol`; the SDK does not create a parallel commit path.

```python
from himmelcad import CanonicalTransactionBuilder, HimmelcadClient

client = HimmelcadClient(transport)
client.negotiate(required_capabilities=("document.read", "document.write"))

for entity in client.iter_entities(max_pages=100):
    print(entity.id, entity.revision)

transaction = CanonicalTransactionBuilder().delete(expected_entity_ref).build()
plan = client.validate(transaction)
# A confirmation grant is opaque, short-lived and issued by the host. The SDK
# only forwards it; it never creates or interprets one.
client.commit(transaction, confirmation_grant=host_issued_grant)
```

Property queries are chunked over exact `EntityVersionRef` values. An empty property list intentionally requests all registered canonical properties, matching the Rust core. Journal/entity iterators have a configurable `max_pages` guard and reject non-advancing cursors.

Large payloads are exposed as bounded, read-only leases. Always use their sync or async context manager so release occurs deterministically. `lease.numpy()` is available through the optional `himmelcad[numpy]` extra and returns a read-only array after hash, shape, endian and byte-length validation.

Regenerate with `python3.12 scripts/generate-automation-sdk.py`. CI/stale checks use `python3.12 scripts/generate-automation-sdk.py --check`; this regenerates into a temporary directory and also fails closed when pinned canonical Rust/TypeScript contracts drift.
'''


def outputs(schema: dict[str, Any]) -> dict[str, bytes]:
    errors = "\n".join(f"    {snake(code).upper()} = {code!r}" for code in schema["errors"])
    return {
        "README.md": README_TEMPLATE.encode(),
        "pyproject.toml": PYPROJECT.encode(),
        "src/himmelcad/__init__.py": INIT_TEMPLATE.encode(),
        "src/himmelcad/models.py": model_source(schema).encode(),
        "src/himmelcad/errors.py": ERRORS_TEMPLATE.format(members=errors).encode(),
        "src/himmelcad/leases.py": LEASES_TEMPLATE.replace("__MAX_SHAPE_ELEMENTS__", str(schema["limits"]["maxShapeElements"])).encode(),
        "src/himmelcad/client.py": CLIENT_TEMPLATE.format(
            limits=repr(schema["limits"]),
            method_capabilities=repr({name: definition.get("capability") for name, definition in schema["methods"].items() if definition.get("capability") is not None}),
            app_method_capabilities=repr(schema["methods"]["app.protocol"]["capabilityByRequestMethod"]),
        ).encode(),
        "src/himmelcad/py.typed": b"",
    }


def verify_contract_sources(schema: dict[str, Any]) -> dict[str, str]:
    paths = [REPOSITORY_ROOT / relative for relative in schema["contractSources"]]
    missing = [str(path) for path in paths if not path.is_file()]
    if missing:
        raise RuntimeError(f"automation contract sources are missing: {missing!r}")
    for relative, expected in schema["contractSourcePins"].items():
        actual = sha256((REPOSITORY_ROOT / relative).read_bytes())
        if actual != expected:
            raise RuntimeError(f"canonical contract shape drifted for {relative}: expected {expected}, received {actual}; review and update the automation schema")
    mutation_source = (REPOSITORY_ROOT / "packages/@himmelcad/data/src/generated/CanonicalEntityMutation.ts").read_text()
    edit_source = (REPOSITORY_ROOT / "packages/@himmelcad/data/src/generated/CanonicalEntityEdit.ts").read_text()
    source_operations = set(re.findall(r'"operation": "([^"]+)"', mutation_source))
    schema_operations = set(schema["$defs"]["CanonicalEntityMutation"]["properties"]["operation"]["enum"])
    source_edits = set(re.findall(r'"kind": "([^"]+)"', edit_source))
    schema_edits = set(schema["$defs"]["CanonicalEntityEdit"]["properties"]["kind"]["enum"])
    if source_operations != schema_operations or source_edits != schema_edits:
        raise RuntimeError("automation mutation DTOs drifted from generated @himmelcad/data contracts")
    app_source = (REPOSITORY_ROOT / "packages/@himmelcad/app/src/canonicalProtocol.ts").read_text()
    for method in schema["methods"]["app.protocol"]["capabilityByRequestMethod"]:
        if f"'{method}'" not in app_source:
            raise RuntimeError(f"app.protocol method {method!r} is absent from the canonical TypeScript contract")
    return {str(path.relative_to(REPOSITORY_ROOT)): sha256(path.read_bytes()) for path in paths}


def generate(schema_path: Path, output: Path) -> None:
    schema_bytes = schema_path.read_bytes()
    schema = json.loads(schema_bytes)
    contract_inputs = verify_contract_sources(schema)
    generated = outputs(schema)
    for relative, data in generated.items():
        destination = output / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
    manifest = {
        "schemaId": schema["properties"]["schemaId"]["const"],
        "schemaSha256": sha256(schema_bytes),
        "generatorVersion": GENERATOR_VERSION,
        "generatorSha256": sha256(Path(__file__).read_bytes()),
        "minimumPython": "3.12",
        "contractInputs": contract_inputs,
        "outputs": {relative: sha256(data) for relative, data in sorted(generated.items())},
    }
    (output / "generator-manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")


def check(schema_path: Path, output: Path) -> int:
    with tempfile.TemporaryDirectory(prefix="himmelcad-sdk-check-") as temporary:
        expected = Path(temporary)
        generate(schema_path, expected)
        relative_paths = set(json.loads((expected / "generator-manifest.json").read_text())["outputs"])
        relative_paths.add("generator-manifest.json")
        stale = [relative for relative in sorted(relative_paths) if not (output / relative).is_file() or (output / relative).read_bytes() != (expected / relative).read_bytes()]
        if stale:
            print("stale generated Python SDK files:")
            for relative in stale:
                print(f"  {relative}")
            return 1
    print("generated Python SDK is current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        return check(args.schema.resolve(), args.output.resolve())
    generate(args.schema.resolve(), args.output.resolve())
    print(f"generated HimmelCAD Python SDK in {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
