/**
 * Service worker registration and update state. The worker (`sw/sw.js`,
 * generated by `scripts/postbuild.mjs`) precaches the whole app — HTML, JS,
 * CSS, fonts, the OCCT and planeGCS WebAssembly modules — under a cache named
 * after the build's content hash, so the app starts offline after the first
 * load.
 *
 * Updates never replace a running app silently: a new worker installs in
 * the background and waits; the user is offered "Reload to update"
 * (`WebChrome.tsx`), which activates it and reloads (the `beforeunload`
 * guard still asks about unsaved changes).
 */
import { create } from 'zustand';

export interface PwaState {
  /** The browser reports no network. */
  offline: boolean;
  /** A new version finished installing and waits for a reload. */
  updateReady: boolean;
  /** This load installed the first service worker: the app now works offline. */
  offlineReady: boolean;
  /** No service worker support (or a non-secure origin): the app works only online. */
  unsupported: boolean;
  /** Activates the waiting version and reloads the page. */
  applyUpdate: () => void;
  dismissOfflineReady: () => void;
}

let waiting: ServiceWorker | null = null;
/** The user asked for the waiting version (Reload): its takeover reloads the page. */
let updateRequested = false;

export const usePwaStore = create<PwaState>((set) => ({
  offline: typeof navigator !== 'undefined' && navigator.onLine === false,
  updateReady: false,
  offlineReady: false,
  unsupported: false,
  applyUpdate: () => {
    if (!waiting) {
      location.reload();
      return;
    }
    updateRequested = true;
    waiting.postMessage({ type: 'SKIP_WAITING' });
  },
  dismissOfflineReady: () => set({ offlineReady: false }),
}));

function track(worker: ServiceWorker | null, hadController: boolean): void {
  if (!worker) return;
  const settle = () => {
    if (worker.state !== 'installed') return;
    if (hadController) {
      waiting = worker;
      usePwaStore.setState({ updateReady: true });
    } else {
      usePwaStore.setState({ offlineReady: true });
    }
  };
  settle();
  worker.addEventListener('statechange', settle);
}

/** Registers `sw.js` next to the page (relative: works at any base path). */
export function registerServiceWorker(): void {
  window.addEventListener('online', () => usePwaStore.setState({ offline: false }));
  window.addEventListener('offline', () => usePwaStore.setState({ offline: true }));
  if (!('serviceWorker' in navigator) || !window.isSecureContext) {
    usePwaStore.setState({ unsupported: true });
    return;
  }
  const hadController = navigator.serviceWorker.controller !== null;
  let reloading = false;
  let controlled = hadController;
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    if (!updateRequested) {
      // The first install claims the page: no reload. A new version activated from another
      // tab: this page still runs the old code, so it offers the reload too.
      if (controlled) usePwaStore.setState({ updateReady: true });
      controlled = true;
      return;
    }
    if (reloading) return;
    reloading = true;
    location.reload();
  });
  const url = new URL('sw.js', document.baseURI);
  void navigator.serviceWorker
    .register(url, { updateViaCache: 'none' })
    .then((registration) => {
      if (registration.waiting && hadController) {
        waiting = registration.waiting;
        usePwaStore.setState({ updateReady: true });
      }
      track(registration.installing, hadController);
      registration.addEventListener('updatefound', () =>
        track(registration.installing, navigator.serviceWorker.controller !== null),
      );
      // Look for a new version when the app comes back to the foreground, at most hourly.
      let lastCheck = Date.now();
      document.addEventListener('visibilitychange', () => {
        if (document.visibilityState !== 'visible' || Date.now() - lastCheck < 3_600_000) return;
        lastCheck = Date.now();
        void registration.update().catch(() => undefined);
      });
    })
    .catch(() => usePwaStore.setState({ unsupported: true }));
}

/** The browser shows no prompt for `persist()` (Chromium and WebKit decide silently; Firefox asks). */
const persistIsSilent = (): boolean => !/\bFirefox\//.test(navigator.userAgent);

/**
 * Asks the browser to keep this site's storage (recent projects, recovery, the offline app)
 * under pressure. Only where that happens silently: Firefox would show a permission prompt at
 * start, and nothing may interrupt a user who models by hand (there storage stays
 * "best effort"; the recovery copy and the offline app are rebuilt when evicted).
 */
export function requestPersistentStorage(): void {
  if (!persistIsSilent()) return;
  void navigator.storage?.persist?.().catch(() => false);
}

/**
 * Keeps `<meta name="theme-color">` on the app's background (`--hc-bg-base`), so an installed
 * app's title bar matches the app theme (light, dark, or the system's) instead of the manifest's
 * fixed dark `theme_color`.
 */
export function syncThemeColor(): void {
  const meta = document.querySelector<HTMLMetaElement>('meta[name="theme-color"]');
  if (!meta) return;
  const apply = () => {
    const color = getComputedStyle(document.documentElement)
      .getPropertyValue('--hc-bg-base')
      .trim();
    if (color && meta.content !== color) meta.content = color;
  };
  apply();
  new MutationObserver(apply).observe(document.documentElement, {
    attributes: true,
    attributeFilter: ['class'],
  });
}
