/** Icons of the modelling features/commands (`model/features.ts`, `commands/featureCommands.ts`). */
import {
  AlignVerticalSpaceAround,
  Axis3d,
  CircleDot,
  Eraser,
  Expand,
  FlipHorizontal2,
  Layers,
  Layers2,
  LayoutGrid,
  Move3d,
  Rotate3d,
  RotateCw,
  Route,
  Spline,
  SquareDashed,
  SquareSlash,
  SquareSplitHorizontal,
  Stamp,
  TriangleRight,
  type LucideIcon,
} from 'lucide-react';

import type { ModelingFeature } from '../model/features.js';

export const MODELING_FEATURE_ICON: Record<ModelingFeature['kind'], LucideIcon> = {
  revolve: RotateCw,
  sweep: Route,
  loft: Layers,
  mirror: FlipHorizontal2,
  pattern: LayoutGrid,
  split: SquareSplitHorizontal,
  transform: Move3d,
  rotateAxis: Rotate3d,
  align: AlignVerticalSpaceAround,
  offsetFace: Expand,
  deleteFace: Eraser,
  hole: CircleDot,
  emboss: Stamp,
  draft: TriangleRight,
  rib: SquareSlash,
  thicken: Layers2,
  constructionPlane: SquareDashed,
  constructionAxis: Axis3d,
};

export const MODELING_COMMAND_ICON: Partial<Record<string, LucideIcon>> = {
  'tools.revolve': RotateCw,
  'tools.sweep': Route,
  'tools.loft': Layers,
  'transform.mirror': FlipHorizontal2,
  'transform.pattern': LayoutGrid,
  'tools.split': SquareSplitHorizontal,
  'transform.rotateAxis': Rotate3d,
  'transform.align': AlignVerticalSpaceAround,
  'tools.offsetFace': Expand,
  'tools.deleteFace': Eraser,
  'tools.hole': CircleDot,
  'tools.emboss': Stamp,
  'tools.draft': TriangleRight,
  'tools.rib': SquareSlash,
  'tools.thicken': Layers2,
  'tools.filletFaceEdges': Spline,
  'tools.filletConcave': Spline,
  'tools.filletConvex': Spline,
  'construct.planeOffset': SquareDashed,
  'construct.planeAngle': SquareDashed,
  'construct.planeThreePoints': SquareDashed,
  'construct.midplane': SquareDashed,
  'construct.planeTangent': SquareDashed,
  'construct.axisEdge': Axis3d,
  'construct.axisTwoPoints': Axis3d,
  'construct.axisCylinder': Axis3d,
  'construct.axisPlanes': Axis3d,
};
